### ISSUE TITLE
TypeError: bad operand type for abs(): 'FloatNode'

### ISSUE THREAD

**Issue by MInner** [HIPS/autograd#102]
Hi, your work is totally amazing :) I have been using it for a few weeks already and I faced this "bad operand type" issue recently. I have double-checked everything and I'm not using numpy anywhere. I'm little confused with what exactly might have went wrong and I'd be happy to present any working (well, not working, actually :) ) example, but right now it's just unclear what exactly to copy-paste;

Here's the actual loss, `bk == autograd.numpy` here, `data` and `theta` are `namedtuple` (the packing-unpacking part works just fine with `autograd` here, tested with other losses):

    def predict(self, theta, data):
        const = assert_arr_shape({
            data.X.shape: ('batch_size', self.n_steps, self.n_input_dim),
            data.y.shape: ('batch_size', self.n_hidden_dim)
        })
        h_prev = bk.repeat(theta.h_0[:, bk.newaxis], const.batch_size, axis=1).T
        activation = lambda x: bk.maximum(0, 1-x)
        to_stack = []
        for i in range(self.n_steps):
            input2hidden = bk.dot(data.X[:, i, :], theta.W_input_to_hidden)
            hidden2hidden = bk.dot(h_prev, theta.W_hidden_to_hidden)
            before_activation = (input2hidden + hidden2hidden)
            h_prev = activation(before_activation)
            to_stack.append(h_prev)
        output = bk.stack(to_stack, axis=1)
        assert_arr_shape({output.shape: (None, self.n_steps, self.n_hidden_dim)})
        
        return output

    def loss(self, theta, data):
        pred = self.predict(theta, data)
        last_step_pred = pred[:, -1, :]
        loss = bk.sum(bk.abs(last_step_pred - data.y))
        return loss

The forward pass (`loss(x)`, `x`-ravel'ed everything) executes just fine, but when I try computing the gradient (`autograd.grad(loss)(x)`), this exception raises.

It does indeed tries to apply `abs()` on the np.ndarray that has `FloatNode` objects instead of actual floats in it.

Thank you!

Ben

<details> 
  <summary> spoiler with call stack </summary>
```
   ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/usman/anaconda2/envs/autograd_py3/lib/python3.5/site-packages/autograd/core.py in forward_pass(fun, args, kwargs, argnum)
     30     args[argnum] = merge_tapes(start_node, arg_wrt)
---> 31     try: end_node = fun(*args, **kwargs)
     32     except Exception as e: add_extra_error_message(e)

<ipython-input-33-eba96aa529af> in packed_loss(x, data)
    101             theta = self.__unpack_x(x)
--> 102             return self.loss(theta, data)
    103         return x_init, theta_init, packed_loss

<ipython-input-36-758b87b157e8> in loss(self, theta, data)
     41         last_step_pred = pred[:, -1, :]
---> 42         loss = bk.sum(bk.abs(last_step_pred - data.y))
     43         return loss

/home/usman/anaconda2/envs/autograd_py3/lib/python3.5/site-packages/autograd/core.py in __call__(self, *args, **kwargs)
    132 
--> 133         result = self.fun(*argvals, **kwargs)
    134         if result is NotImplemented: return result

TypeError: bad operand type for abs(): 'FloatNode'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-37-1ccde909e118> in <module>()
     57 
     58 
---> 59 test_rnn()

<ipython-input-37-1ccde909e118> in test_rnn()
     54 
     55     model = BasicRNN(n_hidden_dim=10, n_input_dim=15, n_steps=100)
---> 56     best_theta = model.fit(data)
     57 
     58 

<ipython-input-33-eba96aa529af> in fit(self, data)
     45         # loss_grad = bk.ops.grad(loss)
     46         loss1d_grad = autograd.grad(loss1d)
---> 47         self.__test_run(loss1d, loss1d_grad, x, data)
     48         data_iterator = self.__warp_data_into_iterator(data)
     49 

<ipython-input-33-eba96aa529af> in __test_run(self, loss1d, loss1d_grad, x, data)
     67 
     68             try:
---> 69                 loss1d_grad(x, **data_clim_pack[1])
     70             except:
     71                 print("Error while testing backward pass!")

/home/usman/anaconda2/envs/autograd_py3/lib/python3.5/site-packages/autograd/core.py in gradfun(*args, **kwargs)
     20     @attach_name_and_doc(fun, argnum, 'Gradient')
     21     def gradfun(*args,**kwargs):
---> 22         return backward_pass(*forward_pass(fun,args,kwargs,argnum))
     23     return gradfun
     24 

/home/usman/anaconda2/envs/autograd_py3/lib/python3.5/site-packages/autograd/core.py in forward_pass(fun, args, kwargs, argnum)
     30     args[argnum] = merge_tapes(start_node, arg_wrt)
     31     try: end_node = fun(*args, **kwargs)
---> 32     except Exception as e: add_extra_error_message(e)
     33     return start_node, end_node, tape
     34 

/home/usman/anaconda2/envs/autograd_py3/lib/python3.5/site-packages/autograd/core.py in add_extra_error_message(e)
    411         else:
    412             raise_(AutogradHint, (extra_message, etype, value), traceback)
--> 413     raise_(etype, value, traceback)

/home/usman/anaconda2/envs/autograd_py3/lib/python3.5/site-packages/future/utils/__init__.py in raise_(tp, value, tb)
    412             exc = tp
    413         if exc.__traceback__ is not tb:
--> 414             raise exc.with_traceback(tb)
    415         raise exc
    416 

/home/usman/anaconda2/envs/autograd_py3/lib/python3.5/site-packages/autograd/core.py in forward_pass(fun, args, kwargs, argnum)
     29     args = list(args)
     30     args[argnum] = merge_tapes(start_node, arg_wrt)
---> 31     try: end_node = fun(*args, **kwargs)
     32     except Exception as e: add_extra_error_message(e)
     33     return start_node, end_node, tape

<ipython-input-33-eba96aa529af> in packed_loss(x, data)
    100         def packed_loss(x, data):
    101             theta = self.__unpack_x(x)
--> 102             return self.loss(theta, data)
    103         return x_init, theta_init, packed_loss
    104 

<ipython-input-36-758b87b157e8> in loss(self, theta, data)
     40         pred = self.predict(theta, data)
     41         last_step_pred = pred[:, -1, :]
---> 42         loss = bk.sum(bk.abs(last_step_pred - data.y))
     43         return loss
     44 

/home/usman/anaconda2/envs/autograd_py3/lib/python3.5/site-packages/autograd/core.py in __call__(self, *args, **kwargs)
    131                         tapes.add(tape)
    132 
--> 133         result = self.fun(*argvals, **kwargs)
    134         if result is NotImplemented: return result
    135         if ops:

TypeError: bad operand type for abs(): 'FloatNode'

```
</details>

**Comment by mattjj** [comment]
I think we don't support calling `stack`. Can you try rewriting it with `concatenate` or `hstack`?

We should wrap it in a `primitive` to make this error more transparent (if it is indeed the problem).

**Comment by MInner** [comment]
@mattjj , thank you for such a rapid response! rewriting it with `concatenate` solved the issue

Yes, that would be really great if unsupported pieces of numpy API would somehow tell that they are unsupported :) or at least if there was a list of all supported\unsupported calls somewhere in docs

If you're too busy with implementing new cool features, and there's some manual way of checking if something is supported or not, I can try to come up with this "supported calls list".

(the thing is just so amazingly cool, because it works so smoothly most of the time, that I just want to help, but the first attempt to "just sit and dig into" your code was.. semi-successful, I'd say :) )

**Comment by mattjj** [comment]
We usually do print a specific error when a function is not supported (i.e. that the gradient is not yet implemented), but functions that take lists as input (like `stack` or `concatenate`) are particularly troublesome in how they interact with autograd's boxed values.

The thing I said above about `stack` was wrong (it's already wrapped in a primitive, by the same process everything else gets wrapped, but the error still happens on the forward pass). We'll either need to special-case the error or implement stack in a way that works with autograd (possibly just copying the code of `numpy.stack` into numpy_wrapper.py). Hmm...

**Comment by mattjj** [comment]
I pushed an implementation of `np.stack`. Reopen the issue if there's still a problem.

Glad you like autograd!

**Comment by MInner** [comment]
It still seems like applying `autograd.numpy.abs( .. autograd node.. )` is not always equivalent to `builtins.abs(.. autograd node.. )` - I just had a similar error message as above (but without any `np.stack`s and with recent autograd version from `master`); the error disappeared after I replaced `abs()` with `anp.abs()`; if there is (indeed) some "preferred" way of doing that, the other one might possibly have to raise a warning or something?

**Comment by mattjj** [comment]
I think we might be able to overload it by adding `__abs__` methods to FloatNode and ArrayNode. It may have just been an oversight not to do it.

**Comment by mattjj** [comment]
I just pushed 22ad70b to master which should include support for the builtin `abs` via `__abs__` methods on ArrayNode and FloatNode.
