### ISSUE TITLE
Any solution for consider_constant?

### ISSUE THREAD

**Issue by thjashin** [HIPS/autograd#106]
Hi,

In theano grad, there is an option called consider_constant to avoid calculating gradients further into a variable. Is there any solution for this in autograd?

Thanks,
Jiaxin

**Comment by mattjj** [comment]
Do you mean something that would behave like this?

```python
print grad(lambda x: x*x)(2.5)                     # prints 5.
print grad(lambda x: x*consider_constant(x))(2.5)  # prints 2.5
```

If so, you can get that behavior by using `getval` from autograd.util:

```python
import autograd.numpy as np
from autograd import grad
from autograd.util import getval

consider_constant = getval

print grad(lambda x: x*x)(2.5)                     # prints 5.
print grad(lambda x: x*consider_constant(x))(2.5)  # prints 2.5
```

If that's useful, we should probably add a `consider_constant` function (even if it's just another name for `getval`). One wrinkle is that `getval` doesn't recursively descend into data structures that might contain Nodes, so we might want to write something a bit more general.

**Comment by thjashin** [comment]
Oh yes, thank you. That's indeed what I mean. It seems that now there is no detailed documents for autograd, right? Because it's hard to find that in source code.

And consider_constant is definitely useful because sometimes you need to calculate gradient in this way, for example, in likelihood-ratio estimator.

Actually I don't get the difference between using a primitive and getval. Doesn't primitive do the same thing as replacing x with a value?

**Comment by mattjj** [comment]
Using getval and defining a primitive would do the same thing, the only question is aesthetics.

It's true that we don't have docs, but questions like this help us figure out what we need to write (someday).

**Comment by thjashin** [comment]
Agree that aesthetics matters :) I'll close the issue. Thank you for the reply.
