### ISSUE TITLE
seterr(...='ignore') does not seem to suppress exception raising

### ISSUE THREAD

**Issue by MInner** [HIPS/autograd#110]
The super-common trick to avoid numerical overflow in softmax is to subtract maximal value from vector before actual exponentiation; though, in some cases, it does underflow, but it's okay as soon as we do some numerical regularization like, `x + \epsilon` before applying anything that requires strictly positive input (e.g. `log`), right?

Doing 
```
import autograd
import autograd.numpy as anp
anp.seterr(under='ignore')
import numpy as _np
_np.seterr(under='ignore')
from autograd.core import np as ag_np
ag_np.seterr(under='ignore')
```
before the actual softmax code does not seem to suppress underflow exception raising.

Thank you for your great work :)

**Comment by mattjj** [comment]
Glad you like the project!

Can you give a failing example?

Btw, there's also a [context manager for the same thing](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.errstate.html#numpy.errstate):

```python
with np.errstate(divide='warn'):
    np.arange(3) / 0.
```

**Comment by mattjj** [comment]
This is behaving as expected for me:

```python
from __future__ import division
import autograd.numpy as np
from autograd import grad

def logsumexp(a):
   cmax = np.max(a)
   return np.log(np.sum(np.exp(a - cmax))) + cmax

a = np.array([-4000., -3900., -10., 0., -np.inf, -np.inf])

with np.errstate(under='ignore'):
   print grad(logsumexp)(a)

with np.errstate(under='raise'):
   print grad(logsumexp)(a)
```

**Comment by MInner** [comment]
@mattjj yes, you're right, I also wrote few code snippets and it seems to work as expected; I have been struggling with this issue for a few days, but I can't isolate and reproduce it as a "minimal failing example" too, for some reason; sorry for (most likely) false alarming :( 

I'll update this issue if I succeed in isolating it, but yes - that is basically the same code you posted above, so everything must be okay on autograd side; but thank you very much for such a prompt reply!

off topic: I remember seeing a video with Linus Torvalds giving a talk somewhere, saying that the most exiting part is not the transition from one thousand of active users to a million, but rather first few hundreds that start using and giving their feedback on your work, as you see many people getting excited about your work and starting talking to their co-workers about it, etc :) I hope that autograd is going to get a significant attention, because it really rocks - especially when it comes to fast prototyping and (!) user-friendly debugging a model, I don't know any other library that could do better than autograd

fyi, [here's](http://rll.berkeley.edu/cgt/) another interesting project from Berkley, that attempts to be a "theano done right" with fast compilation, out-of-box palatalization, but no automatic broadcasting (for some reason - that's a feature, not a bug), but it seems to be somewhat [abandoned](https://github.com/joschu/cgt/graphs/contributors) for ~four month already

**Comment by mattjj** [comment]
Thanks for the kind words about autograd!

We keep our eyes on projects that might serve as "backends" for autograd. It's too bad that CGT might be losing steam, but TF is gaining a lot of traction.

I'm going to close this issue for now; reopen it if there is a problem with autograd along these lines.
