### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (50,128) (50,)

### ISSUE THREAD

**Issue by chirag32527** [HIPS/autograd#119]
unable to resolve this error while running lstm.py...it is giving this error from core.py file ...can u help me out with this

**Comment by duvenaud** [comment]
Sure, happy to help.

Which version of autograd are you running?  Did you modify the example?  Can you give a stack trace, or tell us which line is failing?  Which version of Python are you running?

I'd recommend pulling the latest version, since that one runs on my machine.

**Comment by chirag32527** [comment]
its the latest version...I've downloaded today only by using:
sudo pip install autograd

I am using python 2.7.10 version
here is my screenshot preview when i am running lstm.py

![lstm](https://cloud.githubusercontent.com/assets/19971401/16125739/9fa7f90e-3412-11e6-970b-576f139281c9.png)

**Comment by mattjj** [comment]
Can you try cloning the latest version from github? You can do it like this:

```
git clone git@github.com:HIPS/autograd.git
cd autograd
pip install -e .
```

Then try re-running lstm.py.

**Comment by chirag32527** [comment]
![lstm1](https://cloud.githubusercontent.com/assets/19971401/16127578/b4c4353e-341a-11e6-8f4c-24e15ef4a279.png)

see ...having problem with this ...thats why tried with pip

**Comment by mattjj** [comment]
Hmm, try cloning over https instead:

```
git clone https://github.com/HIPS/autograd.git
```

Also, I recommend not using sudo.

**Comment by chirag32527** [comment]
installed using above process.... but still the same error when i run lstm.py...... :(
![lstm2](https://cloud.githubusercontent.com/assets/19971401/16128150/14fba93a-341d-11e6-8db2-70b2574c7bd7.png)
![lstm3](https://cloud.githubusercontent.com/assets/19971401/16128156/1ad5ff54-341d-11e6-900b-31429e1fb26e.png)

**Comment by duvenaud** [comment]
Hmmm.  My other guess is that it's something to do with scipy changing the default of the keepdims argument.

What happens if you add keepdims=True to the call to logsumexp?  Also, what version of scipy are you running?

Thanks for your patience.

**Comment by chirag32527** [comment]
i am using latest version of scipy and when setting or giving keepdims =True , its is giving an error of "unexpected argument/ extra argument given ".
anyway thank u for ur great assistance.

**Comment by duvenaud** [comment]
Are you sure you're using the latest scipy?  On scipy 0.16 and 0.17.1, I can run

```
from scipy.misc import logsumexp
logsumexp(10.0, axis=0, keepdims=True)
```

and it runs fine.

**Comment by mattjj** [comment]
Since we haven't been able to reproduce this problem and we haven't heard any updates, I'm going to close this issue for now.
