### ISSUE TITLE
Obtaining an output being a vector of derivatives.

### ISSUE THREAD

**Issue by joshimar12** [HIPS/autograd#127]
Hi everyone I'm new to python and I recently got this package installed. I'd like to know if there is a way to get the output of a function as long as the a vector containing the different partial derivatives. If there is a user guide that would assist in learning how to use the package may I please be directed to it.

import autograd.numpy as np
from autograd import grad
from autograd import jacobian
from scipy import *
import time

def AutoGreek(S,r,K,T,v,delta):

        z = np.random.normal(0,1)
        return ((S*exp((r - delta - .5*(v**2))*T + (v * z*sqrt(T))) - K)* exp(-r*T))

abdul = grad(AutoGreek)

print abdul(100.0,.05,100.0,1.0,.2,.01)

I want to get the sensitivities with respect to S,r,T and v in the above function.

**Comment by mattjj** [comment]
The best place to get started is the [tutorial](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md).

To get the gradient with respect to all arguments at once, you can use the [multigrad function in convenience_wrappers.py](https://github.com/HIPS/autograd/blob/master/autograd/convenience_wrappers.py#L40-L51).

You probably don't want to use `from scipy import *` at the top of your file; you'll want to use the autograd versions of those functions. You could replace that line with `from autograd.scipy import *`, or you could just bind the module to a name with `import autograd.scipy as sp` and work from there.
