### ISSUE TITLE
problem running examples

### ISSUE THREAD

**Issue by ambushed** [HIPS/autograd#130]
Hello,

I am trying to run the tanh.py example and can't get past 

**import autograd.numpy as np**

The error i am getting is:

> Traceback (most recent call last):
>   File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1531, in <module>
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 938, in run
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/Users/Vlad/Code/autograd/examples/tanh.py", line 2, in <module>
>     import autograd.numpy as np
>   File "/Users/V/Code/autograd/autograd/__init__.py", line 4, in <module>
>     from .convenience_wrappers import (multigrad, multigrad_dict, elementwise_grad,
>   File "/Users/V/Code/autograd/autograd/convenience_wrappers.py", line 4, in <module>
>     import autograd.numpy as np
>   File "/Users/V/Code/autograd/autograd/numpy/__init__.py", line 4, in <module>
>     from . import numpy_grads
>   File "/Users/V/Code/autograd/autograd/numpy/numpy_grads.py", line 352, in <module>
>     anp.matmul.defgrads(make_grad_matmul, [0, 1])
> AttributeError: 'module' object has no attribute 'matmul'

The project interpreter is Anaconda 2 for Mac.

How can I solve this?  

Thanks

Vlad

**Comment by mattjj** [comment]
I think this is probably a numpy version issue; the `matmul` function was added in numpy 1.10.

Can you update your numpy to 1.10 and try again? You should be able to do something like this:

```
conda update conda
conda update --all
```

**Comment by ambushed** [comment]
thanks, solved!
