### ISSUE TITLE
autograd.scipy issues

### ISSUE THREAD

**Issue by Riashat** [HIPS/autograd#131]
I am having issues using scipy with autograd.

import autograd.scipy.stats.norm as norm 
./autograd/examples/build/bdist.macosx-10.9-intel/egg/autograd/scipy/__init__.py in <module>()

ImportError: cannot import name signal

Similarly, with
import autograd.scipy.stats.multivariate_normal as mvn

and with running the given examples such as bayesian_neural_net.py

Traceback (most recent call last):
  File "bayesian_neural_net.py", line 7, in <module>
    import autograd.scipy.stats.norm as norm
  File "build/bdist.macosx-10.9-intel/egg/autograd/scipy/__init__.py", line 3, in <module>
    
  File "build/bdist.macosx-10.9-intel/egg/autograd/scipy/special.py", line 12, in <module>
AttributeError: 'module' object has no attribute 'gammasgn'

Could someone advice me on what the problem is? I do have scipy but can't use

import autograd.scipy
AttributeError: 'module' object has no attribute 'gammasgn'

**Comment by mattjj** [comment]
This might be a scipy version issue. What version are you on? Can you upgrade to the latest?

**Comment by Riashat** [comment]
I have scipy version '0.11.0'

**Comment by mattjj** [comment]
My version is 0.17.1 and the current version on pip is 0.18. I bet upgrading will fix the problem.
