### ISSUE TITLE
autograd with vector valued functions

### ISSUE THREAD

**Issue by ambushed** [HIPS/autograd#132]
Hi there,

Can the outcome of autograd calls be of non-scalar type?  I need to take a gradient of a vector valued function similar to the one below:

```
def func(x):
    prev = 0
    result = []

    for i in range(0,3):
        prev = r = x**i+prev
        result.append(r)
    return np.array(result)
```
Looking at convenience wrappers, i found `jacobian` but couldn't get it to work on my example.

Thanks in advance,

Vlad

**Comment by mattjj** [comment]
That example code works for me with `jacobian`. What's the error you're getting?

Here's the file I ran successfully:

```python
from __future__ import division
import autograd.numpy as np
from autograd import jacobian

def func(x):
   prev = 0
   result = []
   for i in range(0, 3):
      prev = r = x**i + prev
      result.append(r)
   return np.array(result)

print jacobian(func)(3.)
```

**Comment by ambushed** [comment]
My apologies, it does work!  The error was using the non autograd numpy array.

**Comment by mattjj** [comment]
No problem, I thought that might be the case. Good luck!
