### ISSUE TITLE
Stochastic gradient estimation

### ISSUE THREAD

**Issue by act65** [HIPS/autograd#135]
Hey,
Are there any future plans to implement some sort of stochastic gradient estimation into autograd? I am talking about something like [stochastic grad estimation on comp graphs](http://arxiv.org/abs/1506.05254) and [MuProp](http://arxiv.org/abs/1511.05176). So we could propagate gradients through pretty much anything.

Would this be a good use to time? Does it make sense? Is it plausible?

Anyway, I was thinking of getting into this over summer (southern hemisphere), so let me know.
Alex

**Comment by duvenaud** [comment]
Good question.  I did implement IWAE with the low-variance VIMCO gradient estimator:
http://arxiv.org/abs/1602.06725
I think it's a nice example of when you might want to define the gradient of a procedure outside of Numpy.

I just have to clean it up a little before I add to the examples directory, though.

We would love it if you added demos of other estimators.  For myself I like to do it just to learn the ins and outs of these methods.

**Comment by mattjj** [comment]
We also have the reparameterization trick in [some](https://github.com/HIPS/autograd/blob/master/examples/black_box_svi.py) [examples](https://github.com/HIPS/autograd/blob/master/examples/bayesian_neural_net.py), thanks to @duvenaud. I think this method is essentially what the Schulman et al. paper calls the pathwise derivative (PD) (also discussed in Section 7.2 of the REINFORCE paper, and elsewhere). You can also write the score function (SF) estimator easily with autograd, though I don't think we have any in our examples directory.

So you can already use autograd to implement these methods, and we'd like to add more examples. However, you could imagine a different library which takes some abstract representation of an objective function expressed as the expectation of a random variable and automatically rewrites it into one of these Monte Carlo estimates (to which autodiff can be applied). That's the kind of thing that libraries like Edward might do, and those libraries sit on top of autodiff libraries, but it's outside the scope of autograd itself (we don't have abstractions for random variables, etc.). Hopefully using autograd makes these kinds of tools as easy to write as possible!

Does that make sense? Did I get anything wrong?

**Comment by act65** [comment]
Yes, makes sense and probably.

Cool. I'll have a play, nice examples will probably take me abit (still a beginner). Yea, same here (implementing to learn), that's why I wanted to get into autograd/grad estimation.

Oh wow. Edward is cool... Yea, that's what I wanted. Damn. Maybe i'll just write my own version over autograd? 
Anyway, will think about it more in a month or so.
Thanks
