### ISSUE TITLE
Issue w/ gradient of function of gradient

### ISSUE THREAD

**Issue by swiseman** [HIPS/autograd#156]
Hi,

I've noticed that autograd is giving me a different-than-expected result when I try to take the gradient (wrt one set of parameters) of the square of the norm of the gradient (wrt a different set of parameters). For example, when I attempt to use the following code to compute d/dA [ || d/dx x^T A x ||^2 ], with A symmetric,

```python
def quad_score(x, A):
    """
    computes quadratic form: x^T A x
    """
    return np.dot(x, np.dot(A, x))

def qs_grad_norm_sq(A, x):
    """
    computes ||d/dx [x^T A x]||^2
    """
    grad_quad_score = grad(quad_score)
    grad_x = grad_quad_score(x, A)
    return np.dot(grad_x, grad_x)

grad_qs_grad_norm_sq = grad(qs_grad_norm_sq)
```
I do not get 8 A xx^T, as I would expect. Here is a full gist for reproducing the issue: https://gist.github.com/swiseman/a23eaa505fae268c5cf8cb489ed42a7e

It's worth noting that the gradient wrt A returned by autograd _does_ agree with the finite differences obtained when using qs_grad_norm_sq() as above, but qs_grad_norm_sq() seems to be returning values that are very slightly off. Any suggestions? 

Thanks!

**Comment by mattjj** [comment]
Thanks for this excellent question and code.

If autograd agrees with finite differences on the same code, I think the issue might not be with the code or autograd, but rather in some subtleties of the identity you're using for the symbolic computation of the gradient.

Specifically, I couldn't help but notice that if you take the symmetric part of the result of the 8 A xx^T formula, you get the result that autograd (and apparently finite differences) gives you:

```python
# inserted around line 40 of the gist
print 'symmetrized expected:'
symmetrize = lambda X: (X + X.T)/2.
print symmetrize(8*np.dot(A, np.outer(x, x)))
```

prints:

```
d/dA ||d/dx x^T A x||^2:
------------------------------
expected:
[[ 10.68349036   4.54338653  41.4638454 ]
 [ -6.84736057  -2.91198894 -26.57538788]
 [-13.54599686  -5.76072964 -52.57355983]]
symmetrized expected:
[[ 10.68349036  -1.15198702  13.95892427]
 [ -1.15198702  -2.91198894 -16.16805876]
 [ 13.95892427 -16.16805876 -52.57355983]]
AD:
[[ 10.68349036  -1.15198702  13.95892427]
 [ -1.15198702  -2.91198894 -16.16805876]
 [ 13.95892427 -16.16805876 -52.57355983]]
```

From the comments in your gist, you wrote

d/dA tr(4 x' A' A x) = d/dA tr(4 A' A x x') = 8 A xx' (when A symmetric)

but it seems we could also cycle the trace the other way in the first equality to get

d/dA tr(4 x' A' A x) = d/dA tr(4 xx' A' A) = 8 xx' A

I think the code is treating A entirely symmetrically (i.e. passing in A or A.T gives the same answer), resulting in a symmetric gradient, while these symbolic steps in the math are not.

I'll try to report back if I have more time to think about this, but let us know if this symmetry hint helps at all.

**Comment by mattjj** [comment]
Here's another way to compute the gradient symbolically (which my friend James Saunderson pointed out)

d/dx x' A x = A x + (x' A)'= (A + A') x

then d/dA x' (A + A') (A + A') x = 2 (A + A') xx' + 2 xx' (A + A') = Symm(8 A xx')

where Symm(X) = (X + X')/2 takes the symmetric part.

**Comment by swiseman** [comment]
Thanks very much; that's very helpful!
