### ISSUE TITLE
Support for boolean indexing

### ISSUE THREAD

**Issue by ingmarschuster** [HIPS/autograd#159]
I was doing some boolean indexing to avoid numerical overflow/underflow in the following function:

```
from __future__ import division, print_function, absolute_import

import autograd
import autograd.numpy as np
import autograd.scipy as sp

import autograd.scipy.stats as stats

from autograd.numpy import exp, log, sqrt
from autograd.scipy.misc import logsumexp
from autograd.numpy.linalg import inv


def softplus(x):
    lt_34 = (x >= 34)
    gt_n37 = (x <= -36.8)
    neither_nor = np.logical_not(np.logical_or(lt_34, gt_n37))
    rval = np.copy(x)
    #if np.any(lt_34):
    #rval[lt_34] = x[lt_34]
    if np.any(gt_n37):
        rval[gt_n37] = 0
    if np.any(neither_nor):
        rval[neither_nor] = log(1 + exp(x[neither_nor]))
    return rval  
```

now when trying to differentiate a scalar involving `softplus` like in `autograd.grad(lambda x: dsm.softplus(x).sum())(np.ones(4))` I get a `TypeError: only integer arrays with one element can be converted to an index`.
If I'm not mistaken, I think this is a bug wrt the boolean indexing. Thanks, this is a very nice library!

**Comment by mattjj** [comment]
Glad you like the library!

Autograd already does support boolean indexing, but it [doesn't support assignments into arrays](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md). In a case like this one, it might be better to replace your assignment statements with calls to `np.where` or `np.select`:

```python
def softplus(x):
    lt_34 = (x >= 34)
    gt_n37 = (x <= -36.8)
    neither_nor = np.logical_not(np.logical_or(lt_34, gt_n37))
    rval = np.where(gt_n37, 0., x)
    return np.where(neither_nor, log(1 + exp(x[neither_nor])), rval)
```

That function seems to run for me. Does it do what you want?

**Comment by ingmarschuster** [comment]
Wonderful, that does the trick. Thanks so much, also for the "let me google this for you". Take this as evidence that autograd is so easy to use I didn't bother looking for a tutorial.
Actually, I was thinking that autograd should be merged into numpy/scipy at some point as it is so transparent and useful.

**Comment by mattjj** [comment]
That's a great way to look at things! Thanks for the positive feedback.
