### ISSUE TITLE
TypeError: object of type 'ArrayNode' has no len()

### ISSUE THREAD

**Issue by jackkamm** [HIPS/autograd#16]
Thanks for the extremely fast response to the issue raised yesterday! :D

I have another issue/request. In places where one could normally use len() on ndarray, it fails on ArrayNode.

To some extent I can work around this by using ArrayNode.shape[0]. But, I would like to use the function
autograd.numpy.apply_along_axis()
and this function fails, due to a call to len().

**Comment by mattjj** [comment]
Can you paste an error message and/or a minimal example? It looks like [ArrayNode has a `__len__` method](https://github.com/HIPS/autograd/blob/a811a8226e6ddafb78e37f0553c2d8bdc7af2753/autograd/numpy/numpy_extra.py#L33-34).

**Comment by jackkamm** [comment]
Hmm, sorry about that, I can no longer reproduce the TypeError. I think it's because I upgraded to the latest version from github.

**Comment by mattjj** [comment]
That's an easy way to close an issue! Reopen it if the problem comes back :).
