### ISSUE TITLE
is black_box_svi.py from https://github.com/daeilkim/bayesbackprop

### ISSUE THREAD

**Issue by Sandy4321** [HIPS/autograd#161]
is black_box_svi.py from https://github.com/daeilkim/bayesbackprop or vice versa?
I just try understand if there is simpler code for 
Variational Dropout and
the Local Reparameterization Trick
or
Black Box Variational Inference
to study how it works
may you recommend really simple code

**Comment by mattjj** [comment]
David wrote black_box_svi.py and it looks like it was added to the autograd repo on Oct 14 2015, while that other repository added its file on Mar 30 2016, according to GitHub's dates. You might also be interested in David's paper with Ryan [Black-Box Stochastic Variational Inference in Five Lines of Python](https://www.cs.toronto.edu/~duvenaud/papers/blackbox.pdf), which appeared at a NIPS 2015 workshop.

Our examples repo has some pretty good simple examples, though I'm not sure what else is out there!
