### ISSUE TITLE
is there a fragile dependence on garbage collection?

### ISSUE THREAD

**Issue by mattjj** [HIPS/autograd#17]
This test works on the current master:

```python
import autograd.numpy as np
from autograd import grad

print grad(np.linalg.det)(np.eye(3))
```

(It prints an identity matrix.)

But if we just comment out [this `del` statement in grad](https://github.com/HIPS/autograd/blob/a811a8226e6ddafb78e37f0553c2d8bdc7af2753/autograd/core.py#L31) it no longer prints an identity matrix and instead prints something like

```
<autograd.numpy.numpy_extra.ArrayNode object at 0x1092184d0>
```

I think the change in behavior could be because the `tapes` member of any `Node` instance is a `WeakKeyDictionary`, so that a `del` statement which removes a strong reference to some `tape` can have side-effects on many `Node.tapes` members. If that's the case, that behavior is pretty confusing, and it might be fragile and/or very Python-implementation-specific (e.g. is WeakKeyDictionary guaranteed to remove entries immediately, or only on garbage collection passes?).

Why does the behavior apparently change when removing that seemingly-critical `del` statement, and is that a good thing?

**Comment by dougalm** [comment]
Er, yes. You make some great points. I refactored the logic in core earlier this week so that I could remove tape.complete . But I agree, it's much more brittle this way (and no faster, as it turned out). I'll change it back.
