### ISSUE TITLE
autograd.numpy import in Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by alejandrox1** [HIPS/autograd#174]
Hello, I am trying to use autograd. When I try to `import autograd.numpy as np` I get an `ImportError: No module named 'autograd'`. 

I installed autograd using `pip3 install autograd`. The output for this is the following:
```Requirement already satisfied: autograd in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: numpy>=1.10 in /home/alarcj/.local/lib/python3.5/site-packages (from autograd)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.5/dist-packages (from autograd)
Requirement already satisfied: future>=0.15.2 in /usr/local/lib/python3.5/dist-packages (from autograd)

I'm not sure how to fix this.
Thank you,
Jorge

**Comment by mattjj** [comment]
It looks like autograd isn't actually installed (since it can't be imported). Can you try running the pip install command with the `-v` option to see if some error is reported? Also, can you check that you're indeed trying to import it from python3, and that the place where the pip command installs autograd is on the package search path (i.e. `sys.path`)?

**Comment by alejandrox1** [comment]
Running `pip3 install -v autograd` I get the following:

```Requirement already satisfied: autograd in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: numpy>=1.10 in ./.local/lib/python3.5/site-packages (from autograd)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.5/dist-packages (from autograd)
Requirement already satisfied: future>=0.15.2 in /usr/local/lib/python3.5/dist-packages (from autograd)
Cleaning up...
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
Current age based on date: 772205
Freshness lifetime from max-age: 600
The cached response is "stale" with no etag, purging
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 72990
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching b/c date exists and max-age > 0
```


I have been importing from Python3. From my side the installation seemed to work perfectly. Any recommendations?

**Comment by alejandrox1** [comment]
Never mind. Fixed it by doing `python3 -m pip install autograd -v`.

**Comment by mattjj** [comment]
Hmm, not sure what was going on here, but I'm going to close the issue for now and let someone reopen it if this seems like an autograd-specific problem.

**Comment by akhilesh-pandey** [comment]
When I import autograd.numpy I get the following error:
AttributeError: module 'autograd' has no attribute 'builtins'

**Comment by paviabera** [comment]
> Never mind. Fixed it by doing `python3 -m pip install autograd -v`.

This did not solve my problem.

**Comment by habbas3** [comment]
How did you fix the issue?
