### ISSUE TITLE
PyPi name conflict on autograde?

### ISSUE THREAD

**Issue by fansgit** [HIPS/autograd#178]
[Autograde](https://pypi.python.org/pypi/Autograde/0.1.1) is installed by `pip install autograde` instead of the intended [autograde](https://pypi.python.org/pypi/autograd/1.1.7). How to resolve it?

**Comment by mattjj** [comment]
I think the names aren't actually conflicting, since one is autograde (with an e on the end) while ours is just autograd (without an e on the end). Maybe you made a typo?
