### ISSUE TITLE
float() argument must be a string or a number, not 'FloatNode' 

### ISSUE THREAD

**Issue by kciosek** [HIPS/autograd#181]
Since there is no support for numpy.linspace, I was trying to make a following workaround:
```
 def linspace(start, end, num):
     l = autograd.numpy.zeros((num))
     for i in range(num):
         c = i / (num-1)
         v = start * (1-c) + (c) * end
         l[i] = v
     return l
```
This is embedded in an algorithm where start and end depend on the parameters wrt. which we differentiate and num is a fixed constant. Unfortunately, this code produces an error:

`float() argument must be a string or a number, not 'FloatNode'''

in the line ` l[i] = v'.

I may by making a simple mistake here - if someone has a quick fix for my use case, I'd be very grateful.

**Comment by mattjj** [comment]
Autograd doesn't support assignment into arrays. However, you could rewrite your code like this and even avoid the Python-level loop:

```python
def linspace(start, end, num):
    return start + np.arange(num) * (end-start)/(num-1)
```

Both the original and this version have a divide-by-zero problem when `num` is 1, so you might want to check that with an if statement or assertion.

Which argument were you planning to differentiate with respect to? I think this code should work for differentiating with respect to `start` and `end`, though I didn't test it.

Thanks for bringing up the lack of linspace gradients. Hope this comment helped solve your issue, and feel free to reopen if it didn't!

**Comment by dougalm** [comment]
Just added support for numpy.linspace. Don't know how we missed that one.
