### ISSUE TITLE
np.linalg.norm gradient issue

### ISSUE THREAD

**Issue by arjumand44** [HIPS/autograd#183]
Hi, 

I was getting nans at zeroafter evaluating the gradient of a function that was using np.linalg.norm. Couldn't figure it out. After an embarrassingly long time doing other checks, I tried replacing it with a np.sum expression which seemed to work fine. Just wanted to bring it to your attention. 

Thanks, 
Arjumand

Sample Code: 
```import autograd.numpy as np 
import autograd as au 

def f_sum(x):
    return np.exp(-1.0*np.sum((x**2)))

def f_norm(x):
    return np.exp(-1.0*np.linalg.norm(x)**2)

df_sum = au.grad(f_sum)
df_norm = au.grad(f_norm)

x = np.zeros((2,1))

print "f:", f_sum(x), f_norm(x)
#prints 1.0 1.0
print "using sum:"
print df_sum(x) 
#prints [0,0]
print "using norm:"
print df_norm(x)
#prints [nan, nan]
```

**Comment by mattjj** [comment]
Thanks for bringing this up! I think this is the same as #151 (I got caught on the same thing at one point). If I recall correctly, the basic issue is that norm might not be differentiable at zero, but we should probably just choose a convention for it.

I'm going to close this issue but treat it as a +1 to fix #151.
