### ISSUE TITLE
Tutorial and define_gradient.py obsolete?

### ISSUE THREAD

**Issue by rgiordan** [HIPS/autograd#184]
I'm considering using ```autograd``` for a project, and I will want to define my own derivatives.  But I think maybe the tutorial and ```define_gradient.py``` are not up-to-date.  When I run ```define_gradient.py``` (with the minor fix described below), I get the error

```
TypeError: make_grad_logsumexp() takes exactly 2 arguments (5 given)
```

And, indeed, looking at ```numpy_grads.py```, it seems that gradient definitions now take five arguments, not two.  Am I missing something, or has the code changed under the documentation?

A minor point is that grad is no longer in ```core```, so the above example was run with ```from autograd import grad``` instead.
```
from autograd.core import grad, primitive
ImportError: cannot import name grad
```

**Comment by dougalm** [comment]
Thanks for catching that. I just updated `define_gradient.py` and the tutorial. Your guess was right: we changed the interface for defining primitive gradients (which we consider quasi-internal) but we forgot to update the docs and the example.

**Comment by dougalm** [comment]
I should mention that we still keep the old `defgrad` interface for backwards compatibility - it's now just a wrapper around defvjp that raises a deprecation warning. The problem with `define_gradient.py` was that we had changed `defgrad -> defvjp` but hadn't actually updated the rest of the code. I think I might have done a blind search-replace with sed at some point...
