### ISSUE TITLE
Get all derivatives up to certain order

### ISSUE THREAD

**Issue by ingmarschuster** [HIPS/autograd#189]
For computationally fast Taylor approximations, it would be advantageous to compute all derivatives up to a certain order at the same time, caching the numerical values of terms that occur in all of them (because of the chain rule).

**Comment by j-towns** [comment]
Here's how you could do this for scalar to scalar functions:
```python
from autograd import grad_and_aux
from autograd.core import getval

def next_grad(gfun):
        def next_grad_fun(*args, **kwargs):
            top_grad, grads = gfun(*args, **kwargs)
            return top_grad, grads + [top_grad]
        return next_grad_fun

def derivs_up_to_order(fun, order):
    # Returns a function which computes and returns a list of the derivatives of
    # fun up to and including order.

    def dfun(*args, **kwargs):
        ans = fun(*args, **kwargs)
        return ans, [ans]

    for i in range(order):
        dfun = grad_and_aux(dfun)
        dfun = next_grad(dfun)
        
    def return_fun(*args, **kwargs):
        top_grad, grads = dfun(*args, **kwargs)
        return [getval(g) for g in grads]

    return return_fun
```
This would be efficient in the way that you describe. Example usage:
```python
In [3]: def f(x):
   ...:     return x**3
   ...:

In [4]: derivs_up_to_order(lambda x: x**3, order=5)(2.)
Out[4]: [8.0, 12.0, 12.0, 6.0, 0.0, 0.0]
```
I think it would be a bit trickier to write something for non-scalar functions.

**Comment by j-towns** [comment]
@mattjj this issue can surely be closed?

**Comment by mattjj** [comment]
Wow, that's really cool @j-towns. I had missed this (and we still have an unfortunate backlog of issues and PRs...). I wonder if an efficient Taylor expansion function, or multi-order gradient computation like this, would be useful in convenience_wrappers.py.

I'll close this, but I'll also keep it bookmarked in my mind so that we can revisit this code if it comes up again!
