### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (784,10) (128,784) (784,10)

### ISSUE THREAD

**Issue by Kendos93** [HIPS/autograd#197]
Having defined below functions:

def softmax(X):
    return np.exp(X) / np.sum(np.exp(X), axis=1)[:,np.newaxis]

def cost(batch_data, W, batch_target):
    return - np.sum(np.dot(np.log(softmax(np.dot(batch_data,W))),batch_target.T) ) / batch_size 

gradient = grad(cost)

when trying to learn on MNIST dataset:

for epoch in range(num_of_epochs):
    X = np.random.permutation(np.shape(train_data)[0])
    train_data = train_data[X,:]
    train_target = train_target[X]
    for i in range(num_of_batches):
        batch_data = train_data[i:i+batch_size,:]
        batch_target = train_target[i:i+batch_size]
        W -= gradient(batch_data, W, batch_target) * learning_rate

I obtain an error in line "W -= gradient(batch_data, W, batch_target) * learning_rate":

ValueError: operands could not be broadcast together with shapes (784,10) (128,784) (784,10).

The weird thing is that when I substitute gradient with cost, my code works correctly. I have checked the sizes of arrays, and they seem to be ok.

Could you please explain what am I doing wrong? I am new with autograd (and with github, apologies for bad formatting).

Cheers

**Comment by Kendos93** [comment]
I just realized, that the gradient is with respect to the first argument of the cost function, i had to change the order of the arguments.

**Comment by mattjj** [comment]
You can also use `grad(fun, 1)` or `grad(fun, argnum=1)` to get the gradient with respect to the second positional argument (i.e. argument number 1), or any other argument number. Check out the functions in convenience_wrappers.py too, since we have some other convenient ways to compute gradients, like `multigrad` and `multigrad_dict`.
