### ISSUE TITLE
Containers and higher-order grads. 

### ISSUE THREAD

**Issue by med-int** [HIPS/autograd#205]
This is a follow up to #198.

As before, I have to take a gradient through a couple of layers of SGD: I have a base function `f(W; a, b)` from which I define `h(W; b) = SGD(f, a0)` and then `t(W) = SGD(h, b0)` and then I finally want to optimize `t` wrt `W`. 

```python
import autograd.numpy as np
from autograd import grad
from autograd.core import primitive
from autograd.container_types import make_list, make_dict

def grad_test_nested():
  def base_objective(params, local_vars):
    return np.sum(np.matmul(params["W"], local_vars["a"]) +
					   np.matmul(params["W"], local_vars["b"]))

  grad1 = grad(base_objective, argnum=1)
  def objective2(params, local_vars):
    return search(params, local_vars, base_objective, grad1, ["b"], 5)

  grad2 = grad(objective2, argnum=1)
  def objective3(params, local_vars):
    return search(params, local_vars, objective2, grad2, ["a"], 5)


  local_vars_init = {"a": np.random.rand(5, 1), 
  			     "b": np.random.rand(5, 1)}
  params_init = {"W": np.random.rand(2, 5)}


  print("Forward works: {}".format(objective3(params_init, local_vars_init)))
  grad3 = grad(objective3)
  print("Backward works: {}".format(grad3(params_init, local_vars_init)))


def search(params, local_vars, func, gradient, update_vars, num_search_steps):
  learning_rate = 0.1
  for i in range(num_search_steps):
    grad_val = gradient(params, local_vars)
    new_vals = []
    keys = local_vars.keys()
    for k in keys:
      if k in update_vars:
        new_vals.append(local_vars[k] - learning_rate * grad_val[k])
      else:
        new_vals.append(local_vars[k])
    local_vars = make_dict(zip(keys, new_vals)) 
  return func(params, local_vars)
```

This gives me the following: 

```
TypeError: Can't find vspace for type <class 'autograd.numpy.numpy_extra.ArrayNode'>
```

Does this mean that I need a `make_array` primitive? I don't call `np.array` explicitly in my code anywhere, but maybe the problem comes from lines like this, where an array is created implicitly? 

```
 new_vals.append(local_vars[k] - learning_rate * grad_val[k])
```

I messed around with a few versions of`make_array`, but couldn't find one that helped. Any advice? Thanks!

**Comment by mattjj** [comment]
It's actually just a problem with the [`assert_vspace_match` check](https://github.com/HIPS/autograd/blob/eb1ea540d9433d88c465b3f12cf37d06326b49eb/autograd/core.py#L42); if I save your code to `issue205.py` (adding a call to `grad_test_nested ()` at the bottom) and then run `python -O issue205.py` to disable assertions, the code works. 

I think you've uncovered an issue with our type checking there, or rather an incompatibility with the way I wrote `make_dict`. It's harmless to turn off the type checking for now (either by commenting out that line or by disabling assertions with `-O`), but we should probably patch up our type system here.

**Comment by mattjj** [comment]
I think I got it: there's no problem with the type system, of course! It was my mistake in defining the vjp for `_make_dict`, which needed a call to `make_list`. I'll push a fix in a moment.

**Comment by med-int** [comment]
Yep - that does it! Thanks again for all your help!
