### ISSUE TITLE
kron cannot handle 1D arrays

### ISSUE THREAD

**Issue by treforevans** [HIPS/autograd#209]
It seems that `autograd.numpy.kron` cannot handle 1-dimensional input arrays. This following example works where the inputs are made 2-dimensional
```
import autograd.numpy as np
from autograd import grad
x_test = np.array([1., 2., 3., 4.])
obj_fun = lambda x: np.sum(np.kron(np.atleast_2d(x[:2]),np.atleast_2d(x[2:])))
g = grad(obj_fun)
print g(x_test)
```
however if the inputs are 1D then an error is raised
```
obj_fun = lambda x: np.sum(np.kron(x[:2],x[2:]))
g = grad(obj_fun)
print g(x_test)
```
Output:
```
autograd/numpy/numpy_grads.pyc in <lambda>(blockrow)
    169 def grad_kron(argnum, G, ans, vs, gvs, A, B):
    170     def blocks(G):
--> 171         return map(lambda blockrow: anp.split(blockrow, A.shape[1], 1),
    172                                     anp.split(G,        A.shape[0], 0))
    173     flat = lambda lst: [item for sublist in lst for item in sublist]

IndexError: tuple index out of range
```

**Comment by mattjj** [comment]
Thanks for opening this! It made me take another look at our tensordot vjp definition, and it was unnecessarily complicated and really slow. With @slinderman's help, we have a much better implementation now, which handles the 1D (and 0D) cases. Plus it's much faster!
