### ISSUE TITLE
Gradient of numpy.maximum

### ISSUE THREAD

**Issue by guyemerson** [HIPS/autograd#212]
The gradient of numpy.maximum is inconsistent:

`autograd.grad(numpy.maximum, 0)(1., 1.)` returns `1.0`

`autograd.grad(numpy.maximum, 1)(1., 1.)` returns `0.0`

I do realise that the gradient of the maximum function is discontinuous at this point (when the two arguments are equal), but since the function is symmetric, it would make sense for the gradients to be symmetric as well.  The former behaviour (returning `1.0`) is probably more helpful, e.g. in the case of gradient descent.

**Comment by mattjj** [comment]
I think this behavior is only in older versions of autograd; can you try upgrading?

Here's the current behavior (on master and I believe also on the current pip version):

```
In [3]: grad(np.maximum, 0)(1., 1.)
Out[3]: 0.5

In [4]: grad(np.maximum, 1)(1., 1.)
Out[4]: 0.5
```

See #141 and [Dougal's fix on that issue](https://github.com/HIPS/autograd/pull/141#issuecomment-240917243).

**Comment by guyemerson** [comment]
I have v1.1.9 installed, which is the current pip version.

I'm running this with Python 3.5.2 (Anaconda 4.1.1), numpy 1.12.0, on Windows 64-bit.

**Comment by mattjj** [comment]
Thanks for checking! I just pushed 1.10 to pip. Can you upgrade and try again? If there's still a problem, it might be possible that you have two versions of autograd installed.

**Comment by guyemerson** [comment]
I just upgraded numpy and autograd, but I'm still getting the old behaviour.  I also checked autograd.__path__ after importing it, and it's using the new version.

**Comment by mattjj** [comment]
Oh, I think you might have forgotten `import autograd.numpy as np`:

```
In [1]: from autograd import grad

In [2]: grad(np.maximum, 0)(1., 1.)
Out[2]: 1.0

In [3]: grad(np.maximum, 1)(1., 1.)
/Users/mattjj/packages/autograd/autograd/core.py:16: UserWarning: Output seems independent of input.
  warnings.warn("Output seems independent of input.")
Out[3]: array(0.0)

In [4]: import autograd.numpy as np

In [5]: grad(np.maximum, 0)(1., 1.)
Out[5]: 0.5

In [6]: grad(np.maximum, 1)(1., 1.)
Out[6]: 0.5
```

**Comment by guyemerson** [comment]
Thank you!  I missed that line in the tutorial.
