### ISSUE TITLE
Bug in einsum grad?

### ISSUE THREAD

**Issue by pschulam** [HIPS/autograd#242]
Hi,

First, thanks for the great software! I use it regularly.

I've run into a possible bug in the gradient function for numpy's einsum. Here's a reproducible example for my system (pip environment file is attached to this issue).

```{python}
import autograd
import autograd.numpy as np

rng = np.random.RandomState(0)
x = rng.normal(size=(3, 2, 3, 2))

def f(x):
    y = np.einsum('abcd->bd', x)
    return np.sum(y**2)

print(autograd.grad(f)(x))
```

It appears that the indexing operation [here](https://github.com/HIPS/autograd/blob/master/autograd/numpy/numpy_grads.py#L406) triggers the exception. `naked_summed_dims` is a tuple, but I believe it should be a list.

Is this fix as easy as changing `naked_summed_dims` to `list(naked_summed_dims)` in the index? If so, I'm happy to submit a PR.

Thanks for your help!

[env.txt](https://github.com/HIPS/autograd/files/1072367/env.txt)

**Comment by mattjj** [comment]
Thanks, @pschulam! Your diagnosis was right on the money, so I just went ahead and applied the fix you suggested.

PRs are welcome in the future! For future reference, the best protocol is to add a failing test as well as a fix, like I did in 51dff80. We try to keep to that, though we're not always perfect!

**Comment by mattjj** [comment]
Oh, and thanks for the kind words about autograd!

**Comment by pschulam** [comment]
Great, thanks for the quick fix!

In the future I'll go ahead and submit a PR directly.
