### ISSUE TITLE
scipy and hessian-vector-product

### ISSUE THREAD

**Issue by jackkamm** [HIPS/autograd#25]
A very minor issue but thought I'd bring it up.

scipy.optimize.minimize expects hessian_vector_product(args, vector).

However, the hessian_vector_product in autograd returns a function like
hessian_vector_product(vector, args).

So for compatibility with scipy.optimize.minimize it would be more convenient to swap the order of the parameters.

But I am not so familiar with other optimizers in Python, and perhaps they expect the hessian_vector_product to be parametrized differently.

**Comment by jackkamm** [comment]
Nevermind I realized it would be a pain to return vector_dot_grad with reversed parameters, if len(*args) > 1.

**Comment by mattjj** [comment]
The current implementation effectively prepends the `vector` argument to the `args` list. We could just append it instead. Then the generated function argument list would match the one scipy expects, at least for the case of a single-argument function.

I put a quick mockup in 3780e8d.

What do you guys think? It sounds kinda nice to match what scipy.optimize would expect.

**Comment by mattjj** [comment]
This code seems to work, which is pretty cool:

```python
import autograd.numpy as np
from autograd import grad
from autograd.convenience_wrappers import hessian_vector_product as hvp
from scipy.optimize import minimize

np.random.seed(0)

def rand_psd(n,k=None):
    k = k if k else n
    out = np.random.randn(n,k)
    return out.dot(out.T)


A = rand_psd(2)
b = np.random.randn(2)

def objective(x):
    return 1./2*np.dot(x,np.dot(A,x)) + np.dot(b,x)

x0 = np.array([1.,2.])
minimize(
    objective, x0, method='Newton-CG',
    jac=grad(objective), hessp=hvp(objective),
    options={'xtol': 1e-8, 'disp': True})

print objective(np.linalg.solve(A,-b))
```

**Comment by mattjj** [comment]
Here's some code following the example in the [scipy optimization tutorial](https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html), I think:

```python
import autograd.numpy as np
from autograd import grad
from autograd.convenience_wrappers import hessian_vector_product as hvp
from scipy.optimize import minimize


def rosen(x):
    return np.sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)

x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])

minimize(
    rosen, x0, method='Newton-CG',
    jac=grad(rosen), hessp=hvp(rosen),
    options={'xtol': 1e-8, 'disp': True})
```

**Comment by jackkamm** [comment]
Nice, I like it :)

**Comment by duvenaud** [comment]
Great, thanks for bringing this up.  When I wrote hessian_vector_product, I didn't realize that any scipy optimization routines could use it.  Thanks for the patch, Matt.  I updated the dosctring and merged it.
