### ISSUE TITLE
"stack" operation is too slow

### ISSUE THREAD

**Issue by jleahy** [HIPS/autograd#255]
The way the "stack" operation is currently implemented (including row_stack and column_stack) it invokes array(x) for each item of the input. This creates an object array (because the input is not an ndarray, it's an ArrayNode), which given the input array might have millions of entries is very very slow.

You can achieve the same thing (in the case of column_stack) with concatenate followed by reshape, so it seems odd that the stack function behaves so much worse. At least if it's expected it might be worth a note in the documentation.

Here's an example of the problem:

```python
import autograd.numpy as np
import autograd

def test_one(x):
    a = np.sin(x)
    b = np.cos(x)
    c = np.concatenate((a, b)).reshape((-1, 2))
    return np.sum(c)

def test_two(x):
    a = np.sin(x)
    b = np.cos(x)
    c = np.column_stack((a, b))
    return np.sum(c)

x = np.zeros(1000000)

# both are quick
print(test_one(x))
print(test_two(x))

# this is quick
test_one_grad = autograd.grad(test_one)
print(test_one_grad(x))

# this never terminates
test_two_grad = autograd.grad(test_two)
print(test_two_grad(x))
```

**Comment by shoyer** [comment]
This tripped me up today as well. It's worth noting that the slowness only comes up for the backwards pass, when the input is an `ArrayNode`.

I ended up making my own version of stack that avoids the `autograd.numpy.array()` call:
```
def stack(arrays, axis):
  if not arrays:
      raise ValueError('need at least one array to stack')

  shapes = set(arr.shape for arr in arrays)
  if len(shapes) != 1:
      raise ValueError('all input arrays must have the same shape')

  result_ndim = arrays[0].ndim + 1
  if not -result_ndim <= axis < result_ndim:
      raise IndexError('axis {0} out of bounds [-{1}, {1})'.format(axis, result_ndim))
  if axis < 0:
      axis += result_ndim
      
  sl = (slice(None),) * axis + (None,)
  return autograd.numpy.concatenate([arr[sl] for arr in arrays], axis=axis)
```
(This is literally the same function from autograd/numpy, except I removed the line `arrays = [array(arr) for arr in arrays]`.)

It seems like the general fix might be is to allow `autograd.numpy.array()` (at least inside the `stack` functions) to pass through `ArrayNode` objects?
