### ISSUE TITLE
use of np.add.at in autograd

### ISSUE THREAD

**Issue by krey** [HIPS/autograd#263]
I apologise in advance, this is not an issue with autograd, I'm doing something unsupported.

My numpy is too old to have `np.add.at` in it. Thankfully, it is only used once, in the definition of `untake`, so I can change the line:
`np.add.at(A, idx, x)`
to
`A[idx] += x`

There is a clear difference in semantics though, in the case that `idx` contains repeated indices.

From my naive understanding of the autograd internals, the only time I call `untake` is when I'm differentiating `np.concatenate`, and it doesn't look like that involves any repeated indices.

I would really appreciate if you could tell me whether making the above substitution is "safe".

Many thanks,

krey

**Comment by j-towns** [comment]
Hi there. Untake is actually used when differentiating take, which is the function used for _indexing_ numpy arrays. For example the derivative of the following function will involve untake:
```python
def f(x):
    x_0 = x[0]  # <-- This will call take
    return x_0
```
If none of the indexing that you do involves repeated indices, then you should be safe to replace that line as you suggest.

**Comment by krey** [comment]
Many thanks, Jamie
