### ISSUE TITLE
restoring `elementwise_grad`

### ISSUE THREAD

**Issue by mattjj** [HIPS/autograd#281]
@matthewdhoffman and others have convinced me that we should restore the `elementwise_grad` function (possibly with a better name).

Basically, I think `grad` and `elementwise_grad` should both exist and have almost the same implementation; the only difference would be that `grad` would raise an error for non-scalar-valued functions. (The docstrings would also be different, and `elementwise_grad` could explain that it returns the diagonal elements of the Jacobian under the promise that the Jacobian is diagonal, etc.)

I think having that behavior in `grad` is confusing and might hide bugs in users' code that they would otherwise immediately notice.

Thoughts?

**Comment by dougalm** [comment]
Yes, strongly agree!
