### ISSUE TITLE
Wrong definition of tanh in README

### ISSUE THREAD

**Issue by bgavran** [HIPS/autograd#317]
In the README in the description of the tanh function, shouldn't there be `-2x` instead of `-x` in the definition?

[Wiki reference](https://en.wikipedia.org/wiki/Hyperbolic_function).

**Comment by dougalm** [comment]
Thanks for catching that. Don't know how we missed it all these years.

**Comment by Metaxal** [comment]
This doesn't seem to be fixed yet in the code that generates the plot:
https://github.com/HIPS/autograd/blob/master/examples/tanh.py

Though the plot does look nicer with the faulty definition ;)
