### ISSUE TITLE
Returned variational params are all NaN's

### ISSUE THREAD

**Issue by anataraj** [HIPS/autograd#323]
I am running a Bayesian logistic regression model with layer_sizes = [175, 1]. My activation function is a sigmoid. The returned VI parameters are all NaN's with run time warnings,

1. autograd/core.py:81: RuntimeWarning: divide by zero encountered in log
2. autograd/core.py:81: RuntimeWarning: divide by zero encountered in true_divide
3. autograd/numpy/numpy_grads.py:20: RuntimeWarning: invalid value encountered in multiply anp.multiply.defvjp(   lambda g, ans, vs, gvs, x, y : unbroadcast(vs, gvs, y * g))

My guess is that the returned probabilities are very small leading to numerical unstability. The piece of code that computes the log likelihood, which triggers these warnings, is log_lik = np.sum(np.log(label_probabilities)). Do you happen to know how small these probabilities can be before hitting a numerical underflow? Is there an elegant way to handle this issue?

I am new to autograd. I apologize if this is not where I should be posting this error. Any help is appreciated.

**Comment by anataraj** [comment]
Never mind. Figured it out.

**Comment by mattjj** [comment]
If you have time, can you explain what the issue was? It might be helpful to others who come across this issue.

We weren't able to look into this because we've been managing a big merge, but it's great to hear that you sorted things out already!

**Comment by anataraj** [comment]
**Problem**: While computing the log likelihood (log_lik = np.sum(np.log(label_probabilities))) very small probabilities (<= 1e-60) led to numerical instability when taking the log.

**Failed Approach**: I attempted to take a look at these values before determining a cutoff but I was unable to view entries within a autograd.numpy.numpy_extra.ArrayNode object. How do you view the entries in a Arraynode object?

**Fix**: Added np.maximum(label_probabilities, 1e-60) before computing likelihood. This way probability values below a threshold of 1e-60 were replaced by 1e-60. Again this worked for my dataset, may need to experiment with the threshold.
