### ISSUE TITLE
How to convert defgrad to 1.2?

### ISSUE THREAD

**Issue by jluttine** [HIPS/autograd#332]
I upgraded to version 1.2 and switched from `defgrad` to the new `defvjp`. I didn't modify the actual gradient calculation function in any way. However, unit tests that are using `check_grads` to check the gradient numerically started suddenly failing. Also, some other unit tests that depend on the gradient of the function started failing. So, I guess I've done this conversion somehow incorrectly. I couldn't find any information on how to convert `defgrad` to the new `defvjp` (I only found this guide about switching from old `defvjp` to new `defvjp`: https://github.com/HIPS/autograd/blob/master/docs/updateguide.md#gradient-checking).

So, if I had a function:
```
@primitive
def f(x):
    y = ...
    return y

def df(y, x):
    def g(dy):
        d = ...
        return d
    return g

f.defgrad(df)
```

I just changed `defgrad` method to `defvjp` function, nothing else changed:
```
@primitive
def f(x):
    y = ...
    return y

def df(y, x):
    def g(dy):
        d = ...
        return d
    return g

defvjp(f, df)
```

What am I doing wrong? What else should be modified?

**Comment by mattjj** [comment]
That looks correct to me. Can you make an example that reproduces your error? Or at least post a traceback of the error you're seeing?

One possible explanation is that your `defvjp` call is fine but the check is doing something different; in particular, `check_grads` currently checks to second order by default, and also checks both forward- and reverse-mode by default. Could it be something that changed in the check?

**Comment by jluttine** [comment]
Yep, the issue was that it checked second order. I made it to check first order only and that works. Thanks.
