### ISSUE TITLE
The sigmoid definition in the tutorial is wrong

### ISSUE THREAD

**Issue by ben-ix** [HIPS/autograd#346]
Hi there, 

Just a small point.

Reading through the [tutorial](https://github.com/HIPS/autograd/blob/master/docs/tutorial.md), the definition of sigmoid is given in terms of tanh as

```
def sigmoid(x):
    return 0.5*(np.tanh(x) + 1)
```

But should it not be

```
def sigmoid(x):
    return 0.5*(np.tanh(x/2) + 1)
```

For example sigmoid(1) with the first method gives ~0.88, with the second method gives the expected ~0.73.

This obviously isn't a huge issue but could be misleading if people just used the example code without double checking!

**Comment by mattjj** [comment]
Thanks for catching this!
