### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by untom** [HIPS/autograd#35]
Autograd does currently not support Python3... is there any chance of a Py3 compatible version, or is this not a priority right now?

**Comment by mattjj** [comment]
Check out #10, which has some work on this.

**Comment by untom** [comment]
Awesome! I should've checked there before. Any ETA on when this might be merged?

**Comment by mattjj** [comment]
No sure. I don't think the main authors use Python 3, but expressing interest like this might serve as motivation.

I just rebased the commits from #10 onto the current master and pushed them to the py3 branch (057d4d3). All the tests pass on my python2 setup.

**Comment by kcarnold** [comment]
I made one minor change based on that branch to fix one last thing on Python 3, so I think it's ready to go.

**Comment by mattjj** [comment]
Merged! If there are problems, let's reopen #10 instead of this one.

**Comment by untom** [comment]
Awesome! :)
