### ISSUE TITLE
Documenting CuPy wrapper progress

### ISSUE THREAD

**Issue by ericmjl** [HIPS/autograd#353]
Starting this issue to document progress on wrapping CuPy.

- [x] `import autograd.cupy as cp`
- [x] instantiate arrays from scalars, lists, and tuples.

```python
cp.array(1)
cp.array([1, 2])
cp.array([1, 3]) + cp.array([1, 1])
```

- [x] check that gradients work

```python
import autograd.cupy as cp
from autograd import elementwise_grad as egrad

def f(x):
    return cp.sin(x)

def g(x):
    return x + 2

df = egrad(f)
dg = egrad(g)

a = cp.array([1, 1])

print(f(a))
print(df(a))

print(g(a))
print(dg(a))

```

- [x] Check that higher derivatives work.

```python
import autograd.cupy as cp
from autograd import elementwise_grad as egrad
import numpy as np

a = cp.arange(-2 * np.pi, 2 * np.pi, 0.01)

def sin(x):
    return cp.sin(x)

dsin = egrad(sin)
ddsin = egrad(dsin)

sin(a)
dsin(a)
ddsin(a)
```
- [ ] Fix `ValueError: object __array__ method not producing an array`. 
- [ ] Run tests for all of the CuPy wrapped functions.

**Comment by ericmjl** [comment]
Thanks @duvenaud! I'd love to get input from you on this; also, I might ping both you/Matt/Dougal for help when I get stuck :smile:.

**Comment by ericmjl** [comment]
Current progress: 

```

In [1]: import autograd.cupy as cp
   ...: from autograd import elementwise_grad as egrad
   ...:
   ...: def f(x):
   ...:     f = cp.sin(x)
   ...:
   ...: df = egrad(f)
   ...:
   ...: a = cp.array([1, 1])
   ...:
   ...: f(a)
   ...: df(a)
   ...:
/home/ericmjl/github/software/autograd/autograd/tracer.py:14: UserWarning: Output seems independent of input.
  warnings.warn("Output seems independent of input.")
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/github/software/autograd/autograd/core.py in vspace(value)
    232     try:
--> 233         return VSpace.mappings[type(value)](value)
    234     except KeyError:

KeyError: <class 'NoneType'>

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-1-a00fa8ae48c0> in <module>()
     10
     11 f(a)
---> 12 df(a)

~/github/software/autograd/autograd/wrap_util.py in nary_f(*args, **kwargs)
     18             else:
     19                 x = tuple(args[i] for i in argnum)
---> 20             return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
     21         return nary_f
     22     return nary_operator

~/github/software/autograd/autograd/differential_operators.py in elementwise_grad(fun, x)
     31 def elementwise_grad(fun, x):
     32     vjp, ans = _make_vjp(fun, x)
---> 33     if vspace(ans).iscomplex:
     34         raise TypeError("Elementwise_grad only applies to real-output functions.")
     35     return vjp(vspace(ans).ones())

~/github/software/autograd/autograd/core.py in vspace(value)
    238             raise TypeError("Can't find vector space for value {} of type {}. "
    239                             "Valid types are {}".format(
--> 240                                 value, type(value), VSpace.mappings.keys()))
    241
    242 class SparseBox(Box):

TypeError: Can't find vector space for value None of type <class 'NoneType'>. Valid types are dict_keys([<class 'autograd.core.SparseObject'>, <class 'list'>, <class 'tuple'>, <class 'dict'>, <class 'numpy.ndarray'>, <class 'float'>, <class 'numpy.float64'>, <class 'numpy.float32'>, <class 'numpy.float16'>, <class 'complex'>, <class 'numpy.complex64'>, <class 'numpy.complex128'>, <class 'cupy.core.core.ndarray'>])
```

Probably because of `cupy_wrapper`:

```python
@notrace_primitive
def metadata(A):
    return A.shape , A.ndim# , _cp.result_type(A), _cp.iscomplexobj(A)
    # return _cp.ndim(A)
```

What I think is happening: The interface that accepts the result of `metadata(A)`'s return statement requires all four things. `numpy` implements `result_type(A)` and `iscomplexobj(A)`, but `cupy` doesn't right now. I've pinged the `cupy` devs about the latter.

**Comment by ericmjl** [comment]
@duvenaud @matjj I'm a bit lost on this issue here. Not sure how to handle VSpace mappings. Do you have any guidance?

**Comment by mattjj** [comment]
Sorry for the slow responses! We've gotten a bit behind on issues, but we hope to catch up soon.

Do you have a repository or branch I can clone to reproduce the issue?

From the example code, it looks like you might be missing a `return` statement in the body of `f`, which in Python causes a function to return `None`, which in turn could explain the error you're seeing (differentiating a function that returns None). Sometimes it's easiest to overlook the simplest things!

**Comment by ericmjl** [comment]
OMG you're right! I was missing a return statement. Thanks for catching that, Matt! I kept worrying that I broke something when modifying the cupy code.

**Comment by ericmjl** [comment]
Here's where I'm at right now:

```python
In [1]: import autograd.cupy as cp
   ...: from autograd import elementwise_grad as egrad
   ...:
   ...: def f(x):
   ...:     return cp.sin(x)
   ...:
   ...: def g(x):
   ...:     return x + 2
   ...:
   ...: df = egrad(f)
   ...: dg = egrad(g)
   ...:
   ...: a = cp.array([1, 1])
   ...:
   ...: print(f(a))
   ...: print(df(a))
   ...:
   ...: print(g(a))
   ...: print(dg(a))
   ...:
[0.84147098 0.84147098]
[0.54030231 0.54030231]
[3 3]
[1 1]
```

**Comment by ericmjl** [comment]
Next challenge up, making sure that higher order derivatives work.

**Comment by ericmjl** [comment]
Current progress:

```python
import autograd.cupy as cp
from autograd import elementwise_grad as egrad
import matplotlib.pyplot as plt
import numpy as np

a = cp.arange(-2 * np.pi, 2 * np.pi, 0.01)

def sin(x):
    return cp.sin(x)

dsin = egrad(sin)
ddsin = egrad(dsin)

sin(a)
dsin(a)
ddsin(a)
```

Output:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-cc225bfc2ab7> in <module>()
     14 sin(a)
     15 dsin(a)
---> 16 ddsin(a)

~/github/software/autograd/autograd/wrap_util.py in nary_f(*args, **kwargs)
     18             else:
     19                 x = tuple(args[i] for i in argnum)
---> 20             return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
     21         return nary_f
     22     return nary_operator

~/github/software/autograd/autograd/differential_operators.py in elementwise_grad(fun, x)
     30 @unary_to_nary
     31 def elementwise_grad(fun, x):
---> 32     vjp, ans = _make_vjp(fun, x)
     33     if vspace(ans).iscomplex:
     34         raise TypeError("Elementwise_grad only applies to real-output functions.")

~/github/software/autograd/autograd/core.py in make_vjp(fun, x)
      8 def make_vjp(fun, x):
      9     start_node = VJPNode.new_root()
---> 10     end_value, end_node =  trace(start_node, fun, x)
     11     if end_node is None:
     12         def vjp(g): return vspace(x).zeros()

~/github/software/autograd/autograd/tracer.py in trace(start_node, fun, x)
      8     with trace_stack.new_trace() as t:
      9         start_box = new_box(x, t, start_node)
---> 10         end_box = fun(start_box)
     11         if isbox(end_box) and end_box._trace == start_box._trace:
     12             return end_box._value, end_box._node

~/github/software/autograd/autograd/wrap_util.py in unary_f(x)
     13                 else:
     14                     subargs = subvals(args, zip(argnum, x))
---> 15                 return fun(*subargs, **kwargs)
     16             if isinstance(argnum, int):
     17                 x = args[argnum]

~/github/software/autograd/autograd/wrap_util.py in nary_f(*args, **kwargs)
     18             else:
     19                 x = tuple(args[i] for i in argnum)
---> 20             return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
     21         return nary_f
     22     return nary_operator

~/github/software/autograd/autograd/differential_operators.py in elementwise_grad(fun, x)
     33     if vspace(ans).iscomplex:
     34         raise TypeError("Elementwise_grad only applies to real-output functions.")
---> 35     return vjp(vspace(ans).ones())
     36 
     37 @unary_to_nary

~/github/software/autograd/autograd/core.py in vjp(g)
     12         def vjp(g): return vspace(x).zeros()
     13     else:
---> 14         def vjp(g): return backward_pass(g, end_node)
     15     return vjp, end_value
     16 

~/github/software/autograd/autograd/core.py in backward_pass(g, end_node)
     19     for node in toposort(end_node):
     20         outgrad = outgrads.pop(node)
---> 21         ingrads = node.vjp(outgrad[0])
     22         for parent, ingrad in zip(node.parents, ingrads):
     23             outgrads[parent] = add_outgrads(outgrads.get(parent), ingrad)

~/github/software/autograd/autograd/core.py in <lambda>(g)
     65                     "VJP of {} wrt argnum 0 not defined".format(fun.__name__))
     66             vjp = vjpfun(ans, *args, **kwargs)
---> 67             return lambda g: (vjp(g),)
     68         elif L == 2:
     69             argnum_0, argnum_1 = argnums

~/github/software/autograd/autograd/cupy/cupy_vjps.py in <lambda>(g)
    122 defvjp(acp.log10,  lambda ans, x : lambda g: g / x / acp.log(10))
    123 defvjp(acp.log1p,  lambda ans, x : lambda g: g / (x + 1))
--> 124 defvjp(acp.sin,    lambda ans, x : lambda g: g * acp.cos(x))
    125 defvjp(acp.cos,    lambda ans, x : lambda g: - g * acp.sin(x))
    126 defvjp(acp.tan,    lambda ans, x : lambda g: g / acp.cos(x) **2)

cupy/core/core.pyx in cupy.core.core.ndarray.__mul__()

cupy/core/elementwise.pxi in cupy.core.core.ufunc.__call__()

cupy/core/elementwise.pxi in cupy.core.core._preprocess_args()

TypeError: Unsupported type <class 'autograd.cupy.cupy_boxes.ArrayBox'>
```

My current thoughts: the CuPy ArrayBox is not supported by CuPy the way the NumPy ArrayBox is supported by NumPy. Is this right, @mattjj? Is this something that I should ping the cupy team about, or is it something that can be fixed here?

**Comment by ericmjl** [comment]
@mattjj @duvenaud I'm not quite sure what to do about the following:

https://github.com/cupy/cupy/issues/923#issuecomment-362907009

It looks like CuPy won't automatically cast array-like items to arrays.

Maybe what needs to be done is to pass in `x._value` (or one of `Box`'s attributes that hold the array values) to each of the `acp.func(...)`s?

**Comment by jermwatt** [comment]
Hi @ericmjl - I would like to help out here, and have students who can help out as well.  Do you have a list of items that you are working on (in addition to the issue above) or a sense of other 'to dos' that you could share?

**Comment by ericmjl** [comment]
Hi @jermwatt! Thank you for pinging in :smile:

At the moment, the biggest barrier to the CuPy wrapper is that I can't get higher order derivatives working. If it's something you're up for, I'm happy to do an asynchronous email chat to get you and your students up to speed.

**Comment by jermwatt** [comment]
@ericmjl great!  I didn't appreciate that things are solid for first order derivative based affairs!  Have there been any large (or large-ish) experiments done performing e.g., gradient descent to minimize some loss function?   Is [your fork here](https://github.com/ericmjl/autograd) the place to get started tinkering?

**Comment by ericmjl** [comment]
@jermwatt yes, that is the exact place to begin :smile:. I haven't yet done any experiments to do gradient descent stuff with the CuPy wrapper, although in [my own playground](https://github.com/ericmjl/autograd-fun) I have done it for `autograd.numpy`. Since it's possible to basically `import cupy as np`, your students may find it instructive to try those "simplest complex examples" out (I'm assuming they're undergraduate students?).

**Comment by jermwatt** [comment]
@ericmjl great!

I have done quite a few experiments using `autograd.numpy` as well!  Its an excellent tool for helping students understand 'how stuff inside the blackbox works' - 'stuff' for me being machine learning / deep learning / optimization - as it requires such minimal 'barriers to entry' for new users, and allows them to easily build things themselves.  [See my sandbox here - actively in development!](https://jermwatt.github.io/mlrefined/).   The sandbox includes a good chunk of optimization algos (e.g., first and second order methods) and machine learning components (e.g., linear and nonlinear regression / classification / autoencoders, multilayer perceptrons / batch normalization / convnets / RNNs,...) written entirely in `numpy` / `autograd`.

I've found `numpy.autograd` to work quite well speed-wise for gradient-based training using MNIST-sized datasets on CPUs, and want to get a sense of how big we can go data-wise employing `cupy`.  

On the students side - likely a mix of undergrads / masters!

**Comment by ericmjl** [comment]
@jermwatt wow, love the sandbox that you have! I'd love to continue the discussion here re: CuPy. Love the flexibility that autograd affords me, I've been experimenting with graph CNNs, and have my own pseudo-PyTorch-like package for building custom convolution modules. Wanted to use CuPy for the same reasons: potentially there are a bunch of graphs that I might encounter that are super big too, and I'd like to have the matrix ops done on the GPU instead. 

What is your rough timeline for hacking on CuPy? I have no particular time pressure at the moment, but I'd love to see it progress (even if in little incremental bits) over time. Depending on whether things go well, I might be getting an intern over the summer, and hacking on `autograd.cupy` might be one of the primary projects I have her work on, as it may come in handy for my work.

**Comment by jermwatt** [comment]
- Great!  Sounds like we're sympatico on that front!
- Rough timeline for hacking on CuPy: start the first week of April, hope to have 2 students onboard assisting for 10 weeks (one academic quarter here).  Potential to get a student to assist over the summer as well.

**Comment by ericmjl** [comment]
@jermwatt: Awesome stuff! I just interviewed the potential intern, everything looks great and is lining up well, just have to get final paperwork filled in before I can confirm. Intern's potential timeline at work will be mid-May to mid-August. Looking forward to hacking together on this!

**Comment by ericmjl** [comment]
@jermwatt thanks to some help from @dougalm, I have a path forward on 2º derivatives! Going to push up to my branch soon. cc: @mattjj @duvenaud

**Comment by ericmjl** [comment]
Running the tests for CuPy, there's at least some progress!

```
tests/test_cupy.py ...FFFFFFFFFF...FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF....FF.FFFFFFFF.FF.FF..FFFFFFFFFFFFFFFFFFFFFF.FFFFFF.F                                                                               [100%]
```

**Comment by ericmjl** [comment]
I just added a new issue to solve -- the CuPy wrapper's `__array__` method does not produce an array. This means we can't do:

```python
In [0]: a = cp.arange(1, 10)

In [1]: np.array(a)
Out[1]: ValueError: object __array__ method not producing an array
```

**Comment by ericmjl** [comment]
Going to close this issue thread as it's getting long, and it's not really an issue. Going forth, I will be documenting CuPy wrapper progress separately.
