### ISSUE TITLE
Missing np.polynomial.polynomial module implementation

### ISSUE THREAD

**Issue by madanh** [HIPS/autograd#354]
### Background: 
I'm trying to use sampyl as almost-drop-in replacement for emcee. Sampyl uses autograd as drop-in for numpy. 

### Issue:
Python returns an error
`AttributeError: 'module' object has no attribute 'polynomial'`
 in functions using  `np.polynomial.polynomial.polyval()`. 
Aparently the `polynomial` module of numpy is not implemented.

### Info:
A link to the polynomial module docs:
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.polynomials.polynomial.html

### A question to devs:
Just being curious, is it on your to do list?

**Comment by Hamed-Aghapanah** [comment]
conda remove numpy
conda install numpy=1.13

**Comment by madanh** [comment]
2 years, time to close ;)

**Comment by Hamed-Aghapanah** [comment]
I faced this problem yet :)
