### ISSUE TITLE
Using autograd

### ISSUE THREAD

**Issue by tynanseltzer** [HIPS/autograd#364]
I'm trying to find coefficients of a function f(y) and the w such that d^2y/dt^2 + w^2y = f(y) matches some given data set. To do this, I'm using scipy's odeint and gradient descent, with the following code

f = open('foo', 'r')
t = f.readline().rstrip().split()
real = f.readline().rstrip().split()
real = list(map(float,real))
t = list(map(float,t))
#t =  t = np.linspace(0, 50, 500)

def objective(params, step):
    sol = odeint(osc, q0, t, args=(params[0],params[1],params[2], params[3]), full_output = 0)
    real = np.array(real)
    error = np.sum((sol[:,0]-real)**2)
    return error
def osc(q, t, w, coef1,coef2,coef3):
    f = np.poly1d([coef1,coef2,coef3])
    x, y = q
    dqdt = [y, -w**2*x +f(x)]
    return dqdt
w = 1.0
coef1 = 0.0
coef2 = 0.0
coef3 = 0.0

params =(w,coef1,coef2,coef3)
q0 = [2,1]

def callback(params, step, g):
    if step % 1000 == 0:
        print("Iteration {0:3d} objective {1}".format(step, objective(params, step)))
        
print(type(grad(objective)))
params = adam(elementwise_grad(objective), params, step_size=0.001, num_iters=5001, callback=callback)        

However, the type passed into objective by autograd (ArrayBox) seems to violently disagree with odeint.  ValueError: setting an array element with a sequence.
Is there anything I can do to assuage this, or is there another way I could approach the problem?

**Comment by echo66** [comment]
I think the solution might be similar to this: https://github.com/HIPS/autograd/issues/365

By the way, put your code inside a code block. That way it would be way simpler to read.

**Comment by duvenaud** [comment]
That's a cool application of autograd!  However,
1) As mentioned above, differentiating through a named argument isn't supported.
2) We haven't yet implemented the gradient for ```odeint```.  I don't think it'd be too hard, though.  If someone wants an example to work from, I know that the Stan package supports differentiation through ODE solvers.
