### ISSUE TITLE
TypeError when using a scalar

### ISSUE THREAD

**Issue by anataraj** [HIPS/autograd#386]
Perhaps this is blatantly obvious but I cant seem to get autograd to work on finding gradients for a scalar. The below code throws a "*** TypeError: ufunc 'xlogy' not supported for the input types, ..." What is wrong with variable p's type?

----------------------------------------------
```
import autograd.numpy as np
from autograd.scipy.special import scipy
from autograd import grad
from scipy.optimize import minimize

def logpmf(p):
        k = 33
        n = 100
        return -scipy.stats.binom.logpmf(k, n, p)

x0 = np.array([0.0])
result = minimize(logpmf, x0=x0, jac=grad(logpmf), method='CG')
print("Found minimum at {0}".format(result.x))
```

**Comment by duvenaud** [comment]
We haven't yet implemented the gradient for ```binom.logpdf```.  If you'd like to add them, the gradients for ```scipy.stats.poisson``` would probably be a good template to start from:

https://github.com/HIPS/autograd/blob/master/autograd/scipy/stats/poisson.py
