### ISSUE TITLE
numpy.take and duplicate indices

### ISSUE THREAD

**Issue by andrewowens** [HIPS/autograd#39]
Hi,

First of all, thanks for making autograd! It's been extremely useful.  

I noticed though that np.take produces the wrong result if the index array contains duplicate values.  For example, 
`quick_grad_check(lambda x: np.sum(x[[0,0]]), np.array([1.]))`
fails with:
`AssertionError: Check failed! nd=2.0, ad=1.0`

You can fix it by changing a line in `primitive_sum_arrays` (in `numpy_extra.py`) from
`new_array[array.idx] += array.val`
to:
`numpy.add.at(new_array, array.idx, array.val)`.  I'm not sure if this error occurs elsewhere, but it seems to at least fix the problem in all of the cases that I've tried.

**Comment by duvenaud** [comment]
Thanks for the bug report and the fix!
