### ISSUE TITLE
Current release version is not compatible with np.arctan2

### ISSUE THREAD

**Issue by HerculesJack** [HIPS/autograd#419]
Once I installed autograd from pip, and found that the simple code below gets a keyerror:

```
from autograd import grad
import autograd.numpy as np

def fffff(x):
    return np.arctan2(x[1],x[0])

grad(fffff)(np.array([1,1],dtype='float'))
```

But it seems that this has been fixed in the latest source code. I reinstalled autograd from source code and it works, though the version number is still 1.2, same as the release version from pip. So please consider to update the release version.

**Comment by jermwatt** [comment]
Why not define it yourself?   You could define your own primitive, or just piggy-back on the fact that `np.arctan` is already understood by `autograd` and implement a custom arctan2 function via [the definition](https://en.wikipedia.org/wiki/Atan2) using it - like this

```
import autograd.numpy as np

# custom arctan2 function
def my_arctan(x1,x2):
    v = x2/x1
    if x1 > 0:
        return np.arctan(v)
    elif x1 < 0 and x2 >= 0:
        return np.arctan(v) + np.pi
    elif x1 < 0 and x2 < 0:
        return np.arctan(v) - np.pi
    elif x1==0 and x2 > 0:
        return np.pi*0.5
    elif x1==0 and x2 < 0:
        return -np.pi*0.5 
```
I used the above implementation [here](https://jermwatt.github.io/mlrefined/blog_posts/10_Nonlinear_intro/10_5_Unsupervised.html) and it works great.

**Comment by HerculesJack** [comment]
Thanks for your code. Though I've solved this problem with latest version
of autograd.

Jeremy Watt <notifications@github.com> 于2018年10月19日周五 上午1:54写道：
