### ISSUE TITLE
autograd.jacobian fails at simple linear vector function (numpy.dot)

### ISSUE THREAD

**Issue by dezmondgoff** [HIPS/autograd#423]
```
import numpy as np 
import autograd 

def f(x):
    A = np.arange(9, dtype=np.float).reshape(3,3)
    return np.dot(A, x)

jac = autograd.jacobian(f)
x = np.arange(3, dtype=np.float)
print(f(x))
print(jac(x))
```
The above example yields
```
[ 5. 14. 23.]
/usr/lib/python3.7/site-packages/autograd/tracer.py:14: UserWarning: Output seems independent of input.
  warnings.warn("Output seems independent of input.")
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

**Comment by j-towns** [comment]
Try `import autograd.numpy as np` instead of `import numpy as no`.

**Comment by j-towns** [comment]
Hey there, yes all of Numpy's ufuncs are covered and some of the ufuncs in scipy.special and scipy.stats. See [here](https://github.com/HIPS/autograd/blob/master/autograd/scipy/special.py) and [here](https://github.com/HIPS/autograd/tree/master/autograd/scipy/stats) for the covered scipy ufuncs (anything that's wrapped in a `primitive` has at least some of its gradients supported).

If there are other scipy ufuncs you want to use which we don't yet support you might be able to implement their derivative yourself (ufuncs are usually fairly straightforward). Pull requests are very welcome!

**Comment by joshburkart** [comment]
Hi @dezmondgoff, I guess this issue should be closed?
