### ISSUE TITLE
nograd_primitive 

### ISSUE THREAD

**Issue by hoanguc3m** [HIPS/autograd#434]
I did not find the closed issue of nograd_primitive so I open one.
I am reading an old code that has this line
```
from autograd import nograd_primitive
```
So how can I modify the code to ensure that autograd does not take the gradient through it.
Thanks in advance.

**Comment by j-towns** [comment]
Replacing that with
```python
from autograd.extend import notrace_primitive as nograd_primitive
```
might do the trick, but can't guarantee anything without seeing the whole of the code you're trying to fix.

**Comment by hoanguc3m** [comment]
Thank you for the solution. 
I changed the code using numpy and everything is fine.
