### ISSUE TITLE
Error on grad_odeint

### ISSUE THREAD

**Issue by mansura-habiba** [HIPS/autograd#440]
For 
grad_odeint
I am getting the following error 

z = grad_odeint(zt, model,z0,t, func_args=(friction,))
However, I am getting the following error 
---> 21     T, D = np.shape(yt)
     22     flat_args, unflatten = flatten(func_args)
     23 

ValueError: not enough values to unpack (expected 2, got 1)

Any example available for the grad_odeint

**Comment by jermwatt** [comment]
Can you print out your variable `yt`?   This error implies that `yt` is not a 2-D array, but perhaps a scalar.

**Comment by mansura-habiba** [comment]
Thanks for quick response @jermwatt 
So the yt needs to be a 2D array ?
Here are the parameter for my problem
Initial state
y0 =[0, 0, 16.383040885779835, 11.471528727020921]
target state
yt = [16.03,5.78,0,0]

**Comment by jermwatt** [comment]
As written 

`
yt = [16.03,5.78,0,0]
`

is a list (or Python array).   You need to use a `numpy` array e.g.,

`
yt = np.array([16.03,5.78,0,0])
`

if you want to measure the shape via `np.shape`.  Check out a tutorial like e.g., [this one](https://hackernoon.com/introduction-to-numpy-1-an-absolute-beginners-guide-to-machine-learning-and-data-science-5d87f13f0d51) on numpy.
