### ISSUE TITLE
np.savez having trouble?

### ISSUE THREAD

**Issue by rekino** [HIPS/autograd#446]
I am trying to write and later read the parameters learned by autograd. But np.load seems to be deserializing into a wrong type of datatype. I am using the example code in neural_net.py and after loading the optimized_params from .npz file, l2_norm crashes with the error:
"ValueError: operands could not be broadcast together with shapes (784, 200) and (200, 100)

**Comment by jermwatt** [comment]
How about [pickling](https://docs.python.org/2/library/pickle.html)?

**Comment by rekino** [comment]
yes pickling does help. But then whats the best way to save them as numpy arrays? np.asarray() does not help

**Comment by j-towns** [comment]
This seems to be a generic Numpy issue and not specific to Autograd so I'm going to close for now.
