### ISSUE TITLE
Can we compute gradients on the GPU ?

### ISSUE THREAD

**Issue by karanchahal** [HIPS/autograd#464]
I am curious to know if autograd can work on the GPU. Also wanted to know if putting the calculations on the GPU will lead to substantial speed benefits. Can someone please direct me to relevant resources ?

Thanks !

**Comment by jermwatt** [comment]
Yes - try the newly released [JAX](https://github.com/google/jax) - made by the same great folks!   Its a version of autograd that works on GPUs / TPUs.
