### ISSUE TITLE
tensordot and axes

### ISSUE THREAD

**Issue by stefansommer** [HIPS/autograd#466]
As far as I can see, the axis specification of tensordot is ignored when computing derivatives. In this example, the Jacobian is of the wrong sign (it takes derivative of `-x` instead of `x`):

```python
(lambda x: np.tensordot(np.array([1,0]),np.array([[0,-x],[x,0]]),(0,1)))(1.)
>>> array([0., 1.])

jacobian(lambda x: np.tensordot(np.array([1,0]),np.array([[0,-x],[x,0]]),(0,1)))(1.)
>>> array([ 0., -1.])

 >>> check_grads(lambda x: np.tensordot(np.array([1,0]),np.array([[0,-x],[x,0]]),(0,1)))(1.)
Traceback (most recent call last):
...
AssertionError: Derivative (VJP) check of jvp_<lambda> failed with arg
(1.0, array(-0.43170061)):
analytic: -0.1353787902305393
numeric:  0.13537879021567292
```

**Comment by j-towns** [comment]
Thanks a lot for raising this. Having had a look at the [tensordot adjoints](https://github.com/HIPS/autograd/blob/master/autograd/numpy/numpy_vjps.py#L422..L476), they don't look like they're ignoring the axes, so there must be a bug in the way the axes are handled. I'm about to be on holiday for a week but will try to take a look when I get back.

In the meantime, we welcome pull requests if you fancy having a go at fixing. The tensordot tests (which are clearly missing the above case) are [here](https://github.com/HIPS/autograd/blob/master/tests/test_systematic.py#L117..L135).

**Comment by j-towns** [comment]
Great job! Would you like to submit a pull request, or shall I just merge these changes?

**Comment by stefansommer** [comment]
Thanks, I've submitted a pull request.
