### ISSUE TITLE
Numpy FutureWarnings

### ISSUE THREAD

**Issue by martiningram** [HIPS/autograd#468]
Hi there,

First off, thanks for making autograd. It's my new favourite python library and feels like magic a lot of the time!

I notice that numpy 1.15 is throwing a lot of `FutureWarning`s at me when running autograd:

```python
/anaconda2/envs/py3/lib/python3.6/site-packages/autograd/numpy/numpy_boxes.py:13: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  def __getitem__(A, idx): return A[idx]
```

Looks like it's fine for now, but it would be nice to be future-proof. Hopefully not a big change?

**Comment by j-towns** [comment]
Hey Martin,

Thanks for raising. We’d noticed those but haven’t yet looked into fixing.
I expect it won’t be too much work, will try to get round to it in the next
week or two.

**Comment by j-towns** [comment]
Pull requests are always welcome if you fancy having a go yourself 😉.

**Comment by mwetzel7r** [comment]
i was getting this warning as well; i was able to fix it manually by changing:
`def __getitem__(A, idx): return A[idx]` 
to:
`def __getitem__(A, idx): return A[tuple(idx)]`
^ not sure if that change messes anything up in an unexpected way; but it removes the error
- - -
the warning also shows up in `autograd/numpy/numpy_vjps.py` (line 444); and `autograd/scipy/signal.py` (lines 41, 129).
