### ISSUE TITLE
RuntimeWarning: divide by zero encountered in power

### ISSUE THREAD

**Issue by Arka7Z** [HIPS/autograd#472]
```python
def undifferentiated_term(lamda,i,j):
    retval=0.0
    retval=retval+X[0][j,j]
    for k in range(1,i+1):
        retval=retval+(X[k][j,j])*(np.power(lamda,k))
    retval=np.sqrt(retval)
    return retval
def diff_func(i,j):
    f=undifferentiated_term
    for k in range(i):
        gradient=grad(f,0)
        f=gradient
    return gradient(0.0,i,j)
```
In the above code snippet `X` is a dictionary where each value is a numpy matrix, `i` and `j` are iteration indices.
Evaluating the gradient at 0.0 as shown above is giving `RuntimeWarning: divide by zero encountered in power` whereas the value of `k` is always positive and there is no way `lamda` with zero as input is raised to a negative power. 
``` 
RuntimeWarning: invalid value encountered in double_scalars
  anp.power.defgrad(lambda ans, x, y : unbroadcast(ans, x, lambda g : g * y * x ** (y - 1)))
/home/cules/anaconda3/lib/python3.6/site-packages/autograd/numpy/numpy_grads.py:67: RuntimeWarning: invalid value encountered in double_scalars
  anp.multiply.defgrad(lambda ans, x, y : unbroadcast(ans, x, lambda g : y * g))
```
I am unable to understand if there is any reconstruction of the form `x/x` involved and `x` is essentially 0.0. Is there a getaway around it?

**Comment by j-towns** [comment]
Hi there, it looks like you’re using an old version of Autograd, with a bug in the definition of the derivative of `np.power`. Can you try updating Autograd using pip, or installing from the master branch on Github (which is the most up to date).
