### ISSUE TITLE
Use existing VJP inside custom VJP for @primitive function

### ISSUE THREAD

**Issue by clemisch** [HIPS/autograd#488]
Is it possible to use an existing VJP of autograd inside a custom VJP I'm writing for a `@primitive` function?

I think this would open the possibility to parallelize expensive function while still using autograd for their differentiation.

**Comment by duvenaud** [comment]
Yes, it's totally fine.  For instance, this is necessary in the VJP of scipy.integrate.odeint:
https://github.com/HIPS/autograd/blob/master/autograd/scipy/integrate.py

**Comment by clemisch** [comment]
Thank you @duvenaud, I'll have a look at the file :+1:

**Comment by clemisch** [comment]
Do you have a suggestion concerning multiprocessing/general performance and using existing VJPs?

Say I have an expensive function `f` for which there exists a VJP. I can compute the result of `f` in parallel by defining a @primitive, which computes `f` on parts of the input in parallel. 

Now I want to compute the VJP of `f` wrt to the full input. The naive approach would be to compute `autograd.make_vjp` in parallel and constructing the full VJP from these partial VJPs. But if I do this, wouldn't I unnecessarily compute the result of `f` (without being able to use it in the backprop)? 

Is there maybe a "sleeker", more efficient way (albeit deeper in the core of autograd) to use the partial VJPs in parallel?
