### ISSUE TITLE
Unusual behavior of checkpoint

### ISSUE THREAD

**Issue by ksagit** [HIPS/autograd#495]
The following code
```
from autograd import grad, checkpoint
import autograd.numpy as np
def f(x):
    return [x]

x = np.ones(1)
g = lambda x : f(x)[0]

grad(g)(x)

>>> array([1.])
```
Produces 1 as you'd expect. But the slight modification
```
from autograd import grad, checkpoint
import autograd.numpy as np
def f(x):
    return [x]

x = np.ones(1)
g = lambda x : checkpoint(f)(x)[0]

grad(g)(x)

>>> array([0.])
```
Produces 0. I have observed that checkpoint generally does not play well with lists/tuples. Any pointers for resolving this would be really appreciated!

**Comment by j-towns** [comment]
All of Autograd’s operators (including `checkpoint`) can’t automatically handle functions which output python data structures like lists, dicts and tuples.

However there’s an easy way to do the handling manually (which we should really document). You need to import the appropriate data structure from the `autograd.builtins` module and wrap the function’s output, like this:

```python
from autograd import grad, checkpoint
import autograd.numpy as np

from autograd.builtins import list as ag_list

def f(x):
    return ag_list([x])   # wrap output of f

x = np.ones(1)
g = lambda x : checkpoint(f)(x)[0]

grad(g)(x)
```
A similar approach will work for tuples and dictionaries.

**Comment by ksagit** [comment]
Thanks a lot, this solved the issue for me!
