### ISSUE TITLE
scipy.misc.logsumexp is deprecated

### ISSUE THREAD

**Issue by wesselb** [HIPS/autograd#501]
`scipy.misc.logsumexp`, used [here](https://github.com/HIPS/autograd/blob/65c21e2975fd4d0c6e979c248ee4407e94ed15bf/autograd/scipy/misc.py#L7), is deprecated (see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.logsumexp.html)), and currently yields an `AttributeError` if AutoGrad is imported with the latest version of SciPy. Simply changing the import to `scipy.special.logsumexp` should be sufficient (see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.logsumexp.html)).

**Comment by rgiordan** [comment]
Looks like this was fixed in https://github.com/HIPS/autograd/commit/4ec5aede380c5accf20afd4f4a96d59f1a9cd1df?

**Comment by j-towns** [comment]
Indeed it was, if you can install Autograd from the github master branch please do. I’m gonna contact someone to see if we can get an update pushed to PyPI and gonna close this for now since it has been fixed in master.

**Comment by WarrenWeckesser** [comment]
FYI: https://stackoverflow.com/questions/56956362/failed-to-loading-lifelines-result-shows-attribute-error-module-scipy-misc

**Comment by slinderman** [comment]
Any update on when this change will make it into PyPI? It has been breaking my Travis checks on one of my repo's for the past few months.

**Comment by mattjj** [comment]
Sorry for being so slow to update! Yesterday we updated the pypi package to 1.3.

**Comment by slinderman** [comment]
Thanks, Matt!
