### ISSUE TITLE
Broadcasting limited in python function

### ISSUE THREAD

**Issue by jmamath** [HIPS/autograd#504]
Python 3.6
autograd - 1.2 - py_1 - conda-forge

Consider the following code:

```
import autograd.numpy as np 
x = np.linspace(-10,10,100)
def _sigmoid(x):
    return 1 / (1 + np.exp(-1))

sigmoid = lambda x: (1/1+np.exp(-x))

_s = _sigmoid(x)
s = sigmoid(x)
```
If you run it you will find that _s is a single value, whereas s is an array as expected. Why ?

**Comment by clemisch** [comment]
Your definition of sigmoid is wrong. You write `np.exp(-1)` instead of `np.exp(x)`.
