### ISSUE TITLE
Error in getting gradient for `numpy.linalg.matrxi_power'

### ISSUE THREAD

**Issue by Ndonyapour** [HIPS/autograd#523]
I have a function that uses the 'numpy.linalg.matrxi_power' function and when I'm trying to get the gradient of it I'm getting the following error:

import autograd.numpy.linalg as la
import autograd.numpy as np
import autograd.grad as grad
def f(x):
       return np.sum(la.matrix_power(x, 3))
grad_func = grad(func)
x = np.random.rand(10, 10)
grad_func(x)

---------------------------------------
<ipython-input-18-530aa1bf9292> in <module>()
----> 1 grad_func(x)

~/anaconda3/lib/python3.6/site-packages/autograd/wrap_util.py in nary_f(*args, **kwargs)
     18             else:
     19                 x = tuple(args[i] for i in argnum)
---> 20             return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
     21         return nary_f
     22     return nary_operator

~/anaconda3/lib/python3.6/site-packages/autograd/differential_operators.py in grad(fun, x)
     22     arguments as `fun`, but returns the gradient instead. The function `fun`
     23     should be scalar-valued. The gradient has the same type as the argument."""
---> 24     vjp, ans = _make_vjp(fun, x)
     25     if not vspace(ans).size == 1:
     26         raise TypeError("Grad only applies to real scalar-output functions. "

~/anaconda3/lib/python3.6/site-packages/autograd/core.py in make_vjp(fun, x)
      8 def make_vjp(fun, x):
      9     start_node = VJPNode.new_root(x)
---> 10     end_value, end_node =  trace(start_node, fun, x)
     11     if end_node is None:
     12         def vjp(g): return vspace(x).zeros()

~/anaconda3/lib/python3.6/site-packages/autograd/tracer.py in trace(start_node, fun, x)
      8     with trace_stack.new_trace() as t:
      9         start_box = new_box(x, t, start_node)
---> 10         end_box = fun(start_box)
     11         if isbox(end_box) and end_box._trace == start_box._trace:
     12             return end_box._value, end_box._node

~/anaconda3/lib/python3.6/site-packages/autograd/wrap_util.py in unary_f(x)
     13                 else:
     14                     subargs = subvals(args, zip(argnum, x))
---> 15                 return fun(*subargs, **kwargs)
     16             if isinstance(argnum, int):
     17                 x = args[argnum]

<ipython-input-13-7580e05bee78> in func(x)
      1 def func(x):
----> 2     return np.sum(la.matrix_power(x, 3))
      3 
      4 

~/anaconda3/lib/python3.6/site-packages/autograd/tracer.py in f_wrapped(*args, **kwargs)
     43             argnums = tuple(argnum    for argnum, _   in boxed_args)
     44             ans = f_wrapped(*argvals, **kwargs)
---> 45             node = node_constructor(ans, f_wrapped, argvals, kwargs, argnums, parents)
     46             return new_box(ans, trace, node)
     47         else:

~/anaconda3/lib/python3.6/site-packages/autograd/core.py in __init__(self, value, fun, args, kwargs, parent_argnums, parents)
     28     def __init__(self, value, fun, args, kwargs, parent_argnums, parents):
     29         self.parents = parents
---> 30         self.vjp = primitive_vjps[fun](parent_argnums, value, args, kwargs)
     31 
     32     def initialize_root(self, value):

KeyError: <function primitive.<locals>.f_wrapped at 0x2b6acee3f8c8

**Comment by momchilmm** [comment]
It seems that `linalg.matrix_power` is not implemented in autograd, but there's a simple work-around: you can define your own function using `autograd.numpy.dot`. Here's the code that runs:

```
import autograd.numpy as np
from autograd import grad

def matrix_power(x, n):
    y = np.eye(x.shape[0])
    for i in range(n):
        y = np.dot(x, y)
    return y

def f(x):
    return np.sum(matrix_power(x, 3))

grad_func = grad(f)
x = np.random.rand(10, 10)
grad_func(x)
```

**Comment by Ndonyapour** [comment]
Thank you. It worked.
