### ISSUE TITLE
Issue with numpy when trying to install autograd

### ISSUE THREAD

**Issue by mkotsi** [HIPS/autograd#534]
Hello, 

I have been trying to install autograd with pip, but I keep running to an error with numpy that I am not sure how to fix. If it is of any help, I will copy - paste the terminal output from when I run the command "pip install autograd":

Collecting autograd
  Using cached https://files.pythonhosted.org/packages/23/12/b58522dc2cbbd7ab939c7b8e5542c441c9a06a8eccb00b3ecac04a739896/autograd-1.3.tar.gz
Collecting numpy>=1.12 (from autograd)
  Using cached https://files.pythonhosted.org/packages/51/67/8907005262f493e356195bcbd61b41988eecf63cb1d97ea2f6e55fe24205/numpy-1.16.5-cp27-cp27m-macosx_10_9_x86_64.whl
Collecting future>=0.15.2 (from autograd)
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Installing collected packages: numpy, future, autograd
  Found existing installation: numpy 1.8.0rc1
ERROR: Cannot uninstall 'numpy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Any help will be highly appreciated it! 
Thank you very much in advance. 

All the best,
Maria

**Comment by agriyakhetarpal** [comment]
Hi, @mkotsi – apologies on behalf of the erstwhile maintainers that no one responded on this issue; I think this might have been resolved by now and both NumPy + Autograd should get installed in much cleaner ways. Please feel free to ping us on a new issue in case you still face any problems with the installation!
