### ISSUE TITLE
Is np.matmul not supported by Autograd?

### ISSUE THREAD

**Issue by yahmadian** [HIPS/autograd#535]
I get the following error when applying and using autograd's `grad` to a function that uses `np.matmul`:

> TypeError: ufunc 'matmul' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

I installed autograd 1.3 yesterday, using `pip install autograd`, in a python 3.7.4 environment with (original) numpy version 1.16.4 on a Mac (with Clang V4.0.1) (if any of that matters). 

Here's a small repro:
```
import autograd.numpy as np
from autograd import grad

def myfunc(J11):
    J = np.asarray([[J11, 1.5], [2.3, 3.]])
    r = np.asarray([3., 4.])
    
    return np.matmul(J, r)[0]

print(myfunc(1.))

dmyfunc = grad(myfunc)

print(dmyfunc(1.))
```

 It gives the above error (only) after running the last line. And if I replace `np.matmul`   in `myfunc` with `np.dot`, it works fine. I know that you discourage `J.dot(r)` and encourage `np.dot(J, r)`, but I hadn't seen anything discouraging `@`.

**Comment by agriyakhetarpal** [comment]
Hi @yahmadian, I tried this with both the latest released version of `autograd` and the development version, and I wasn't able to reproduce this issue – differentiating `np.matmul` seems to work correctly; I am using NumPy v2.1.3 and Python 3.12 at the time of writing. I shall close this for now, but please don't hesitate to seek any resolutions or to ask for help on any other issues you might face. Apologies for not having responded over the years :)
