### ISSUE TITLE
JVP of slogdet wrt argnums (0,) not defined

### ISSUE THREAD

**Issue by CarloNicolini** [HIPS/autograd#536]
I am trying to compute the derivative of the logdet of a matrix phi(t) with respect to the parameter t.
For example:

import autograd.numpy as np
from autograd import deriv
f = deriv(lambda x : np.linalg.slogdet(x*np.eye(4))[1])(4.0)

Unfortunately though it appears that slogdet has no backpropagation implemented. 
I know I can compute slogdet as trace of matrix log of the matrix Phi(t) and in this case backpropagation is handled correctly, but I am scared of numerical issues.
Any idea?

**Comment by duvenaud** [comment]
The gradient of slogdet is implemented:

https://github.com/HIPS/autograd/blob/7c09501d847621e23c3caa4ea2869db29c5d0711/autograd/numpy/linalg.py#L25

If you post your error message, we might be able to help you debug.
