### ISSUE TITLE
AttributeError: module 'scipy.misc' has no attribute 'logsumexp'...#help

### ISSUE THREAD

**Issue by ghost** [HIPS/autograd#564]
import autograd.scipy.special.linalg as spla
  File "/usr/local/lib/python3.6/dist-packages/autograd/scipy/__init__.py", line 7, in <module>
    from . import misc
  File "/usr/local/lib/python3.6/dist-packages/autograd/scipy/misc.py", line 7, in <module>
    logsumexp = primitive(scipy.misc.logsumexp)
AttributeError: module 'scipy.misc' has no attribute 'logsumexp'

**Comment by agriyakhetarpal** [comment]
This can now be closed, the `logsumexp` function is available for later versions of SciPy in the [`scipy.special`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.logsumexp.html) module.
