### ISSUE TITLE
`np.int` is a deprecated

### ISSUE THREAD

**Issue by madsmpedersen** [HIPS/autograd#565]
https://github.com/HIPS/autograd/blob/master/autograd/numpy/numpy_wrapper.py#L20

throws

DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.

with numpy 1.20.0

Should `_np.int` be removed from the list, replaced with `int` or should the warning just be ignored.

**Comment by j-towns** [comment]
Thanks for pointing this out, and sorry for the slow response!

**Comment by Rajesh083** [comment]
how to resolve this issue. I am getting the same.

**Comment by madsmpedersen** [comment]
It has been fixed (https://github.com/HIPS/autograd/commit/01eacff7a4f12e6f7aebde7c4cb4c1c2633f217d)
