### ISSUE TITLE
defining valid np.array through iterative concatination

### ISSUE THREAD

**Issue by zyzhang1130** [HIPS/autograd#571]
Hi, I have an array defined in the following way:
```
def kernel(x1,x2,l):
    return np.exp(-((x1-x2)**2).sum()/(2*(l**2)))

k_t_X_list = []

for i in range(k-1):
    k_t_X_list.append(np.expand_dims(np.expand_dims(np.asarray(kernel(observation,top_k_history[i+1],l)), axis=0), axis=0))


k_t_X = np.expand_dims(np.expand_dims(np.asarray(kernel(observation,top_k_history[0],l)), axis=0), axis=0)

for i in range(k-1):
    k_t_X = np.concatenate([k_t_X, k_t_X_list[i]], axis=1)
```
I did not create this array using assignment, but I got the following error:
32         except KeyError:
     33             fun_name = getattr(fun, '__name__', fun)
---> 34             raise NotImplementedError("VJP of {} wrt argnums {} not defined"
     35                                       .format(fun_name, parent_argnums))
     36         self.vjp = vjpmaker(parent_argnums, value, args, kwargs)

NotImplementedError: VJP of asarray wrt argnums (0,) not defined

not sure how else should I create this array.

**Comment by j-towns** [comment]
It's `asarrray` that seems to be causing that problem (I'm not sure why its vjp isn't defined though). Maybe try removing the `np.asarrray` call, it looks as though it might not be necessary.

**Comment by zyzhang1130** [comment]
yes it is indeed due to asarrray. thank you so much for your help!
