### ISSUE TITLE
differentiate thorugh nested function

### ISSUE THREAD

**Issue by zyzhang1130** [HIPS/autograd#572]
HI, I would like to confirm that autograd is able to differentiate thorugh nested function. Example:

```
def expo(x)
      return np.exp(-2.0 * x)

def tanh(x):                 
     return (1.0 - expo(x)) / (1.0 + expo(x))

grad_tanh = grad(tanh)   
grad_tanh(1.0)
```

will this work the same way as having 'y = np.exp(-2.0 * x)' in def tanh(x) instead of another function (as the example given in the main page)?

**Comment by j-towns** [comment]
Yes 🙂.

**Comment by zyzhang1130** [comment]
Thank you for your confirmation!
