### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by SmartPycg** [HIPS/autograd#580]
Hi，I failed to run **autograd**'s test cases due to ModuleNotFoundError

![image](https://user-images.githubusercontent.com/105635378/183794474-766ff209-ef78-467e-ac99-db4efb0f1297.png)

I tried to install all the requirements files but some packages were still missing. Can you complete the requirements file or give some other sulutions.

Thanks for your help.
Best,
SmartPycg

**Comment by agriyakhetarpal** [comment]
Hi @SmartPycg, recent releases for Autograd should have fixed this. You should be able to install NumPy and then run the tests using `pytest`. The original report, through your screenshot, indicated the absence of NumPy. Please feel free to open an issue in case you continue to face problems with running the test suite!
