### ISSUE TITLE
Limitations of autograd's custom primitives

### ISSUE THREAD

**Issue by austinhoag** [HIPS/autograd#584]
I am wanting to write a custom primitive that implements a forward pass from a pytorch model. I want it to be a custom primitive so that I can use pytorch to differentiate it because autograd cannot do it due to it not being able to handle pytorch tensors.

However, I am finding a pretty significant limitation of custom primitives that is not mentioned in the docs: the custom primitive cannot return an object such as a pytorch tensor that autograd cannot differentiate. This is true, *even if you give autograd the vector jacobian product of that primitive* and tell autograd not to look inside the primitive. 

Here is a basic example:
```python
import torch
from autograd import grad

@primitive
def myfunc(x):
    x_torch = torch.tensor(x)
    return x_torch**2

def myfunc_vjp(ans,x):
    return 2*x

defvjp(myfunc,myfunc_vjp)

def example_func(x):
    return 1+myfunc(x)

x=np.arange(10)
grad_example = grad(example_func)
grad_example(x)
```
Results in the following error:
```python
TypeError: Can't differentiate w.r.t. type <class 'torch.Tensor'>
```

Then what is the point of `defvjp(myfunc,myfunc_vjp)`? I thought it was so that you could black box off your primitive function.

**Comment by austinhoag** [comment]
For context, I have a library that uses autograd for differentiating other parts of the call stack that aren't Pytorch objects. I have a Pytorch model plugin in the middle of the stack. My options are try to box off the Pytorch plugin using this custom primitive approach or rewrite the library entirely in Pytorch. Option 1 is highly preferred if it is possible.

**Comment by j-towns** [comment]
Try explicitly casting the output of `myfunc`, and the output of `myfunc_vjp`, to NumPy arrays. Note also that `myfunc_vjp` needs to return a function...
```python
In  [1]: import torch
    ...: from autograd import grad
    ...: from autograd.extend import primitive, defvjp
    ...: import autograd.numpy as np
    ...: 
    ...: 
    ...: @primitive
    ...: def myfunc(x):
    ...:     x_torch = torch.tensor(x)
    ...:     return np.array(torch.sum(x_torch ** 2))
    ...: 
    ...: def myfunc_vjp(ans,x):
    ...:     return lambda g: np.array(2 * x * g)
    ...: 
    ...: defvjp(myfunc, myfunc_vjp)
    ...: 
    ...: def example_func(x):
    ...:     return 1 + myfunc(x)
    ...: 
    ...: x=np.arange(10, dtype='float64')
    ...: grad_example = grad(example_func)
    ...: grad_example(x)
Out [1]: array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])
```

**Comment by austinhoag** [comment]
Let me explain *why* I want `myfunc` to return a Pytorch tensor. Here is a common pattern in Pytorch for getting gradients via backprop:
```python
a = torch.tensor([2., 3.], requires_grad=True) # some parameter whose gradient I want
Q = a**2 # some loss function(param) 
external_grad = torch.tensor([1., 1.]) # dQ/dQ
# backprop
Q.backward(gradient=external_grad) # computes vector Jacobian product
# now we can retreive dQ/da
a.grad # should return 2a = 4, 6
```

In my real use case, `Q` contains some Pytorch objects and operations on those objects. Also, `Q` is called from within another function, `example_fun`, which doesn't have any Pytorch statements and whose gradient I am getting using autograd:
```python
def Q(x):
    # some Pytorch operations on x ...
    return x**2 

def example_func(x):
    return 1+Q(x)
```
Since `Q` is not wrapped with `@primitive` here, Autograd will balk at this because of the Pytorch operations inside of `Q`. Once I wrap Q, I need to tell autograd how to get `dQ/dx`. I want to use the Pytorch pattern above to do that, which I will do by using `ans.backward` inside of the vjp function. That will only work is if `ans`, the return value of `Q`, is a Pytorch tensor: 

```python
import torch
from autograd import grad
from autograd.extend import primitive, defvjp
import autograd.numpy as np

@primitive
def Q(x):
    # some Pytorch operations on x ...
    global x_torch
    x_torch = torch.tensor(x,requires_grad=True)
    return x_torch**2

def Q_vjp(ans,x):
    external_gradient = torch.ones(len(x))
    ans.backward(gradient=external_gradient)
    dQdx = x_torch.grad
    print(dQdx)
    return lambda g: np.array(dQdx*g)

def example_func(x):
    return 1+Q(x)

defvjp(Q,Q_vjp)

x=np.arange(10, dtype='float64')
grad_example = grad(example_func)
grad_example(x)
```
The printed value, `print(dQdx)`, is the correct gradient. However, before the code completes I get an error:
```python
Input In [256], in example_func(x)
     20 def example_func(x):
---> 21     return 1+Q(x)

File ~/anaconda3/envs/seldo-pytorch/lib/python3.9/site-packages/autograd/tracer.py:46, in primitive.<locals>.f_wrapped(*args, **kwargs)
     44     ans = f_wrapped(*argvals, **kwargs)
     45     node = node_constructor(ans, f_wrapped, argvals, kwargs, argnums, parents)
---> 46     return new_box(ans, trace, node)
     47 else:
     48     return f_raw(*args, **kwargs)

File ~/anaconda3/envs/seldo-pytorch/lib/python3.9/site-packages/autograd/tracer.py:120, in new_box(value, trace, node)
    118     return box_type_mappings[type(value)](value, trace, node)
    119 except KeyError:
--> 120     raise TypeError("Can't differentiate w.r.t. type {}".format(type(value)))

TypeError: Can't differentiate w.r.t. type <class 'torch.Tensor'>
```
Which to me indicates that issue is that `Q` returns a tensor, which autograd cannot differentiate. This surprises me because by wrapping `Q` with `@primitive` I am explicitly telling autograd *not* to differentiate `Q`. So why is it trying to?

I can get around this by using another global variable, which is inefficient and bad style, but my question still stands
```python
import torch
from autograd import elementwise_grad as egrad
from autograd.extend import primitive, defvjp
import autograd.numpy as np

@primitive
def Q(x):
    # some Pytorch operations on x ...
    global x_torch
    x_torch = torch.tensor(x,requires_grad=True)
    global Q_torch
    Q_torch = x_torch**2
    return x**2

def Q_vjp(ans,x):
    external_gradient = torch.ones(len(x))
    Q_torch.backward(gradient=external_gradient)
    dQdx = x_torch.grad
    print(dQdx)
    return lambda g: np.array(dQdx*g)

def example_func(x):
    return 1+Q(x)

defvjp(Q,Q_vjp)

x=np.arange(10, dtype='float64')
grad_example = egrad(example_func)
grad_example(x)
```

**Comment by tylerflex** [comment]
@austinhoag did you ever figure anything out? Dealing with a similar issue here. Note that with Jax it seems you can have a bit more control over defining your own vjp maker, but you need to register your object as a pytree for things to work properly https://jax.readthedocs.io/en/latest/notebooks/Custom_derivative_rules_for_Python_code.html

**Comment by j-towns** [comment]
The `defvjp` function works by [storing the gradient function in a Python dictionary](https://github.com/HIPS/autograd/blob/c6d81c/autograd/core.py#L42-L44), where the key is the callable returned by `primitive`. I think your setup means the dictionary lookup is not working because the key changes between registering and lookup.

Is it possible for you to do something like this:
```python
import autograd.numpy as np
from autograd import grad
from autograd.extend import primitive, defvjp

class myModel():
    def myfunc(self,x):
        # some Pytorch operations on x ...
        return np.sum(x**2)

    def myfunc_grad(self,ans,x):
        return lambda g: np.array(2*x*g)

m = myModel()

myfunc = primitive(m.myfunc)
defvjp(myfunc, m.myfunc_grad)

def example_func(x,model):
    return 1+myfunc(x)  # This must be the same (same Python object id) myfunc passed to defjvp above

x=np.arange(10, dtype='float64')
grad_example = grad(example_func)
grad_example(x,m)
```

**Comment by j-towns** [comment]
If you can I would also consider moving to using JAX, which supports this functionality but is much better documented.

**Comment by austinhoag** [comment]
Thanks, that solution worked for me. For anyone else interested, it is also possible to put the `defvjp()` call inside of `__init__()` like this:

```python
import autograd.numpy as np
from autograd import grad
from autograd.extend import primitive, defvjp

class myModel():
    def __init__(self):
        myfunc_primitive = primitive(self.myfunc)
        defvjp(myfunc_primitive, self.myfunc_grad)
        
    def myfunc(self,x):
        # some Pytorch operations on x ...
        return np.sum(x**2)

    def myfunc_grad(self,ans,x):
        return lambda g: np.array(2*x*g)

def example_func(x,model):
    return 1+model.myfunc(x) 

m = myModel()
x=np.arange(10, dtype='float64')
grad_example = grad(example_func)
grad_example(x,m)
```

I have looked into JAX some, though not for this purpose. The reason I stay with autograd is that JAX is actually slower for my library's tasks even with vmapping and jitting. I need to play around a bit more with trying to optimize, though, as I suspect there will be a way to restructure my code to make it faster. It does seem like there are many other reasons to move to JAX, so I may try to migrate anyway. 

The last thing that remains to be addressed before I close this is: "why can't the primitive function return a PyTorch tensor, even if I wrap it with `@primitive`?"

**Comment by j-towns** [comment]
>The reason I stay with autograd is that JAX is actually slower for my library's tasks even with vmapping and jitting.

Interesting. JAX used to be pretty slow on CPU, due to large 'dispatch overheads'. Basically launching the correct compiled code for a given function and input requires some logic, which was implemented in Python, but has now been sped up by a C++ implementation. I think for certain things (particularly things which bottleneck on BLAS calls) NumPy (and therefore Autograd) might still be faster though. As you say you can often tune the implementation to whichever library you're using and see some improvements, and there are certain things where having a proper compiler underneath means that jit-compiled JAX will be significantly faster than NumPy.

>why can't the primitive function return a PyTorch tensor, even if I wrap it with @primitive?

Autograd has a small, built-in type system, of what we call `VSpace`s (short for 'vector spaces'). The main definition is [here](https://github.com/HIPS/autograd/blob/c6d81ce7eede6db801d4e9a92b27ec5d409d0eab/autograd/core.py#L188-L229). In order for a Python value to be a valid intermediate in a function that is being differentiated by Autograd (that is an input, or an output, of a `primitive`), its type must have a registered `VSpace`. The `VSpace` for a given Python type tells Autograd how to add elements of that type, how to materialize a 'zero' of that type, and how to multiply that type by a scalar, basically the things you'd expect for a vector space. We don't have `VSpace`s setup for PyTorch Tensors.

The `VSpace` system is actually [extensible](https://github.com/HIPS/autograd/blob/c6d81ce7eede6db801d4e9a92b27ec5d409d0eab/autograd/extend.py), although completely undocumented. You can see how `VSpace`s are defined for NumPy arrays [here](https://github.com/HIPS/autograd/blob/c6d81ce7eede6db801d4e9a92b27ec5d409d0eab/autograd/numpy/numpy_vspaces.py).

**Comment by austinhoag** [comment]
Thanks, that makes sense.
