### ISSUE TITLE
Add np.float128,np.complex256 dtypes to vspaces and boxes registers

### ISSUE THREAD

**Issue by mduschenes** [HIPS/autograd#590]
Please add np.float128 and np.complex256 dtypes to the numpy ArrayBox and ArrayVSpace register of mappings  (Gradients appear to be computed correctly once dtypes are added to lists) Thank you.

https://github.com/HIPS/autograd/blob/81b288e58a93c653295977ad6c588ce2d80205be/autograd/numpy/numpy_boxes.py#L51-L53
https://github.com/HIPS/autograd/blob/81b288e58a93c653295977ad6c588ce2d80205be/autograd/numpy/numpy_vspaces.py#L61-L65

**Comment by j-towns** [comment]
If you can submit a pull request with these changes I'd be happy to merge it.

**Comment by mduschenes** [comment]
Thanks!
