### ISSUE TITLE
unsafe URL

### ISSUE THREAD

**Issue by tomsturges** [HIPS/autograd#595]
Hello, 

There is a URL inside one of the tutorials that has been compromised and redirects to unsafe websites. Please remove. Thank you.
The URL: http://www.intpowertechcorp.com/GDC03.pdf
Inside: https://github.com/HIPS/autograd/blob/master/examples/fluidsim/fluidsim.py

**Comment by duvenaud** [comment]
Thanks for noticing!  I'll also fix this same demo in the dex repo now.
