### ISSUE TITLE
`autograd` 1.6 breaks Apple M-series macOS and Windows builds (module `numpy` has no attribute `float128`)

### ISSUE THREAD

**Issue by agriyakhetarpal** [HIPS/autograd#601]
## Issue

Hi there, `autograd` had a new 1.6 release a few hours ago – where I assume #591 was merged into the release branch, tracked by #590. It added the following to `autograd/numpy/numpy_boxes.py`: 
```python
ArrayBox.register(np.ndarray)
for type_ in [float, np.float128, np.float64, np.float32, np.float16,
              complex, np.complex64, np.complex128, np.complex256]:
    ArrayBox.register(type_)
```
The `np.float128` and `np.complex256` scalars do not exist for NumPy on some platforms including Windows and ARM-based MacOS, i.e., M-series chips ([NumPy docs](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.complex256))

### Relevant log output

```
 File "/.tox/unit/lib/python3.10/site-packages/autograd/differential_operators.py", line 16, in <module>
    import autograd.numpy as np
 File ".../.tox/unit/lib/python3.10/site-packages/autograd/numpy/__init__.py", line 3, in <module>
    from . import numpy_boxes
  File ".../.tox/unit/lib/python3.10/site-packages/autograd/numpy/numpy_boxes.py", line 52, in <module>
    for type_ in [float, np.float128, np.float64, np.float32, np.float16,
  File ".../.tox/unit/lib/python3.10/site-packages/numpy/__init__.py", line 322, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float128'. Did you mean: 'float16'?
```

### A temporary workaround for other users

Add upper bounds to a lower version of `autograd`: 1.5 does not have these changes

### Footnotes

Some other issues I found where this was noted:

1. https://github.com/vivarium-collective/vivarium-core/issues/196
2. https://github.com/mpi4jax/mpi4jax/issues/112

P.S. A way to fix this could be with using `longdouble` instead (and I would be glad to write a PR doing this): https://web.archive.org/web/20151121033150/http://mail.scipy.org/pipermail/scipy-dev/2008-March/008562.html

**Comment by j-towns** [comment]
Thanks for raising. For now I have reverted efecc64389c21ba1b79ec27ae6058a6bcd00e40b and pushed a new release to PyPI. I will implement a proper fix tomorrow, re-enabling float128 and complex256 on systems where they're available.

**Comment by j-towns** [comment]
@agriyakhetarpal thanks for the tip regarding longdouble. I used that and the complex clongdouble and have pushed a new release to PyPI enabling support for those datatypes. Tested with MacOS on both x86 and ARM machines. Thanks again, and lmk if anything is still broken.

**Comment by agriyakhetarpal** [comment]
Looks good to me — it should work now. Thank you for the quick response and fix, @j-towns!
