### ISSUE TITLE
Releasing on Anaconda.org

### ISSUE THREAD

**Issue by richardotis** [HIPS/autograd#63]
Any chance you guys could maintain autograd on https://anaconda.org ? I would like to be able to reference the package in my conda recipe so the conda users of my library can easily install it. I can build autograd myself and host in my custom channel, but it's more likely to be the latest version if the official maintainers do it. :)

I wrote up some notes on my own experiences uploading a library to Anaconda.org here: https://github.com/richardotis/pycalphad/blob/0fdf613116c22740262660db12696804af5e4553/RELEASING.rst

Here's an example conda recipe file: https://github.com/richardotis/pycalphad/blob/0fdf613116c22740262660db12696804af5e4553/conda_recipe/conda.yaml

I drive all my versioning from Git, but it's also possible to hard-code version numbers or pull them fron another source.

**Comment by mattjj** [comment]
If it's easy for you to write a conda recipe for autograd, a pull request would be welcome :)

**Comment by richardotis** [comment]
I'll see what I can do. I'd have to write one anyway to host in my custom channel, so it's not any extra work for me to do it and submit the PR.

**Comment by richardotis** [comment]
Looks like Cython is required for the build, so it'll be slightly trickier to build conda packages for Windows.

**Comment by mattjj** [comment]
Actually, Cython is totally optional! The autograd is written so that it doesn't depend on any extension module code, but there is a bit of optional extension module code that the setup.py tries to build (and proceeds without it if there is any kind of failure). So just pretend there is no mention of Cython!

**Comment by richardotis** [comment]
Is scipy a required dependency? It's not in setup.py but `import autograd.scipy` fails without it.

**Comment by richardotis** [comment]
See #65
