### ISSUE TITLE
Casting from float to int for the purpose of indexing can break things

### ISSUE THREAD

**Issue by kswersky** [HIPS/autograd#71]
This is a bit of a silly example, but numpy indexing requires integers, however this ends up breaking autograd.

```
import numpy as np
import autograd.numpy as anp
from autograd import grad
def fun(W, inds):
   W = anp.concatenate((W, inds), axis=1)
   inds = W[:,-1]
   W = W[:,:-1]
   return W[anp.int64(inds)].sum()

W = np.random.randn(5, 10)
inds = np.ones(5)[:,None]
g = grad(fun)
g(W, inds)
```

produces `TypeError: long() argument must be a string or a number, not 'FloatNode'`

**Comment by mattjj** [comment]
I think the branch I just pushed to has a fix. Can you try checking out the branch int-type-casts-unbox-args and see if it fixes your test cases? (I ran it on the one you pasted but maybe you have more.)

**Comment by kswersky** [comment]
Thanks Matt, it definitely fixes this example! Once you merge that branch we should close this.

**Comment by tylerpayne** [comment]
I am unfortunately encountering this error when trying to go from normalized uv coordinates back to image xy indexes.

```
    uuu = np.int_((uv[:,:,0]*(HEIGHT/2.))+HEIGHT/2.)
    vvv = np.int_((uv[:,:,1]*(WIDTH/2.))+WIDTH/2.)
```

I am using autograd.numpy and have cloned the most recent working copy from this repository. When calling the function this is wrapped there are no errors, but when attempting to call the autograd.grad version of the function I receive the same error as kswersky

TypeError: long() argument must be a string or a number, not 'FloatNode'

**Comment by duvenaud** [comment]
I think we need to wrap `np.int_()`.  In the meantime, I think this will work:

```
uuu = ((uv[:,:,0]*(HEIGHT/2.))+HEIGHT/2.).astype(int)
vvv = ((uv[:,:,1]*(WIDTH/2.))+WIDTH/2.).astype(int)
```

as in this example:
https://github.com/HIPS/autograd/blob/master/examples/fluidsim/fluidsim.py#L43

**Comment by tylerpayne** [comment]
No luck, I've tried every method I can think of to cast the arrays to int, all return the same error.

**Comment by mattjj** [comment]
Have you tried using `np.int64`? The code [wraps that explicitly](https://github.com/HIPS/autograd/blob/d3b866c0daf97b14b32b80e37c31f84471313bdb/autograd/numpy/numpy_wrapper.py#L31), and this test code works for me:

```python
from __future__ import division
import numpy as np
import autograd.numpy as anp
from autograd import grad
def fun(W, inds):
   W = anp.concatenate((W, inds), axis=1)
   inds = W[:,-1]
   W = W[:,:-1]
   return W[anp.int64(inds)].sum()

W = np.random.randn(5, 10)
inds = np.ones(5)[:,None]
g = grad(fun)
print g(W, inds)
```

**Comment by mattjj** [comment]
@tylerpayne, I'm not able to reproduce your error by switching the above test code to use `np.int_`. Can you write a self-contained code snippet that produces the error you're seeing?

**Comment by mattjj** [comment]
After rereading your description, I realized the issue here is different from the OP.

In the code that @duvenaud linked, there's a call to `np.floor` before doing the `astype(int)` thing. Can you try that, or something similar? Since `np.floor` is defined to have a zero gradient, it will probably unbox things so that the `astype(int)` will work on unboxed numpy types.
