### ISSUE TITLE
Array dimension expansion causes segfault

### ISSUE THREAD

**Issue by kswersky** [HIPS/autograd#72]
```
import numpy as np
from autograd import grad
def fun(x):
    return x[:, None].sum()
g = grad(fun)
g(np.random.randn(5))
```
Causes a seg fault. There are other ways to expand the dimensions of an array other than [:, None], but perhaps it should fail more gracefully in this case. I've also verified that it does the same thing with np.newaxis.

**Comment by dougalm** [comment]
Both `x[:, None]` or `x[:, np.newaxis] ` are valid ways to expand dimensions and autograd has always supported them. I can't reproduce the segfault on my machine. What versions of numpy and scipy are you using?

**Comment by kswersky** [comment]
Numpy 1.8.0 and Scipy 0.13. Looks like I should upgrade!

**Comment by mattjj** [comment]
The segfault happens on numpy 1.8.0, 1.8.1, and 1.8.2, but not 1.9.0. Maybe autograd should require numpy>=1.9 (or we could find the bug and work around it).

**Comment by mattjj** [comment]
Oh, numpy's setup.py does require >=1.9 already.

**Comment by mattjj** [comment]
Btw, the segfault happens in [`np.add.at` in `primitive_sum_arrays`](https://github.com/HIPS/autograd/blob/34483b76edfec1def73b79961bbeed6e9b63e1c6/autograd/numpy/numpy_extra.py#L123) when called with these arguments:

```
ipdb> print new_array
[ 0.  0.  0.  0.  0.]
ipdb> print array.idx
(slice(None, None, None), None)
ipdb> print array.val
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
```
