### ISSUE TITLE
Support for `np.diff`

### ISSUE THREAD

**Issue by dhirschfeld** [HIPS/autograd#74]
Hi, great project - very interesting! I'm investigating it's use for evaluating gradients of monte-carlo expectations. One issue I've run into is the lack of support for `np.diff`. Would it be difficult to add this? I've had a poke around but don't think I've got the knowledge/expertise to do so myself. Happy to give it a go if it's beginner level and I can get some pointers...

On another note, is there a mailing-list or gitter chat room for `autograd`?
```python
In [13]: def diff(x):
    ...:     return np.concatenate([x[:1], np.diff(x)])

In [14]: # gradient of dummy function which uses `diff`
    ...: g = grad(lambda x: np.sqrt(diff(x)).sum())

In [15]: g(randn(10))
Traceback (most recent call last):

  File "<ipython-input-15-acc7bd9d5211>", line 1, in <module>
    g(randn(10))

  File "C:\Anaconda3\lib\site-packages\autograd\core.py", line 21, in gradfun
    return backward_pass(*forward_pass(fun,args,kwargs,argnum))

  File "C:\Anaconda3\lib\site-packages\autograd\core.py", line 91, in backward_pass
    og = cast_to_node_type(gradfun(cur_outgrad), parent.node_type, parent.node_value)

  File "C:\Anaconda3\lib\site-packages\autograd\core.py", line 136, in error
    raise NotImplementedError(errstr.format(self.fun.__name__, argnum))

NotImplementedError: Gradient of diff not yet implemented.
```

**Comment by dhirschfeld** [comment]
If there's a workaround in the interim I'd be very happy to hear. I tried manually constructing the diff vector but then you end up with an array/list of `FloatNodes` and you can't seem to do much with them - e.g. taking a sqrt.
```python
In [16]: def diff(x):
    ...:     dx = [x[0]]
    ...:     for idx in range(1, x.size):
    ...:         dx.append(x[idx] - x[idx-1])
    ...:     return np.asarray(dx)

In [17]: # gradient of dummy function which uses `diff`
    ...: g = grad(lambda x: np.sqrt(diff(x)).sum())

In [18]: g(randn(10))
Traceback (most recent call last):

  File "<ipython-input-18-acc7bd9d5211>", line 1, in <module>
    g(randn(10))

  File "C:\Anaconda3\lib\site-packages\autograd\core.py", line 21, in gradfun
    return backward_pass(*forward_pass(fun,args,kwargs,argnum))

  File "C:\Anaconda3\lib\site-packages\autograd\core.py", line 63, in forward_pass
    except Exception as e: add_extra_error_message(e)

  File "C:\Anaconda3\lib\site-packages\autograd\core.py", line 392, in add_extra_error_message
    raise_(etype, value, traceback)

  File "C:\Anaconda3\lib\site-packages\future\utils\__init__.py", line 414, in raise_
    raise exc.with_traceback(tb)

  File "C:\Anaconda3\lib\site-packages\autograd\core.py", line 62, in forward_pass
    try: end_node = fun(*args, **kwargs)

  File "<ipython-input-17-a063cc27b22f>", line 2, in <lambda>
    g = grad(lambda x: np.sqrt(diff(x)).sum())

  File "C:\Anaconda3\lib\site-packages\autograd\core.py", line 163, in __call__
    result = self.fun(*argvals, **kwargs)

AttributeError: 'FloatNode' object has no attribute 'sqrt'
```

**Comment by dhirschfeld** [comment]
For reference, here's a workaround that works but can't be very efficient:
```python
def diff(x):
    D = np.diag(np.ones(x.size)) - np.diag(np.ones(x.size-1), k=-1)
    return np.dot(D, x)
```

**Comment by mattjj** [comment]
I think that new commit b5e5cde should do it. Reopen the issue if there's something amiss. 

I don't think we have a mailing list or gitter chat room. I've never used a gitter chat room. Think that would be a good idea?

Take a look at the commit to see how I implemented the gradient of `diff`, though it's not particularly slick or anything: `diff` is a linear operation, namely multiplication by a matrix like this one on the left:

```
[ 1,  -1,   0,   0]
[ 0,   1,  -1,   0]
[ 0,   0,   1,  -1]
```

so to the compute the reverse-mode gradient we need to multiply the incoming gradient by that matrix on the right. If you transpose that matrix, you can see it looks like computing something like `np.concatenate((-g[0], -np.diff(g), g[-1])).`

**Comment by dhirschfeld** [comment]
Thanks, @matjj - that was fast! I can confirm that it works for me.

Yeah, my ugly workaround was to construct the finite-difference matrix and then let autograd do its magic!

**Comment by dhirschfeld** [comment]
Gitter seems to be the open source tool to use for chat-rooms linked up with GitHub. IMHO it can be  handy to have a higher bandwidth forum than opening GitHub issues and it's better than personal emails because the content is archived and searchable so others can learn from the conversations so hopefully you don't have to repeat yourself. A google-groups forum is another option and arguably better as the conversations are threaded so easier to follow. 

I think all three forums have their place but certainly having either gitter or google-groups in addition to GitHub issues would be useful in fostering discussions with an outside community.

Obviously as the authors you should feel free to use (or not) whatever tools make your lives/work easier.
