### ISSUE TITLE
Bug with `np.diff` gradient for single-element input vectors

### ISSUE THREAD

**Issue by dhirschfeld** [HIPS/autograd#78]
I've tried to debug this but to no avail:

The below implementation of `diff` agrees with `np.diff` so can be used in its place with `autograd`
```python
In [1]: from numpy.testing import assert_almost_equal
   ...: 
   ...: from autograd import elementwise_grad
   ...: import autograd.numpy as np

In [2]: def diff(x):
   ...:     D = np.diag(np.ones(x.size)) - np.diag(np.ones(x.size-1), k=-1)
   ...:     return np.dot(D, x)[1:]
   ...: 
   ...: 

In [3]: x = np.array([ 0.0667,  0.944 ,  1.42  ,  1.7165,  2.177 ])

In [4]: for end in range(x.size, 0, -1):
   ...:     assert_almost_equal(np.diff(x[:end]), diff(x[:end]))
   ...: 
In [5]: 
```
The definitions of the gradients *should* therefore be the same but differ when `x` is of size 1:
```python
In [8]: g1 = elementwise_grad(np.diff)
   ...: g2 = elementwise_grad(diff)
   ...: for end in range(x.size, 0, -1):
   ...:     assert_almost_equal(g1(x[:end]), g2(x[:end]))
   ...: 
<snip>
AssertionError: 
Arrays are not almost equal to 7 decimals

(shapes (0,), (1,) mismatch)
 x: array([], dtype=float64)
 y: array([ 0.])
```
Looking more closely at the arguments:
```python
In [9]: x = x[:1]
   ...: x
Out[9]: array([ 0.0667])

In [10]: np.diff(x)
Out[10]: array([], dtype=float64)

In [11]: g2(x)
Out[11]: array([ 0.])

In [12]: g1(x)
Out[12]: array([], dtype=float64)
```
So `autograd`'s automatic differentiation of the `diff` function gives `array([ 0.])` for a 1-element input vector whereas the gradient of `np.diff` gives an empty array `array([], dtype=float64)`

**Comment by mattjj** [comment]
Handling np.diff([5]) was tricky because the outgrad was a zero-dimensional array (along the axis that was diff'd), and in that case the gradient should just be zero. Try the latest master and let me know if you catch any more bugs!

**Comment by dhirschfeld** [comment]
Thanks again for the fast response! I can confirm that my tests pass with the new version.
