### ISSUE TITLE
Wrapping numpy.int_ and related types can break expected numpy dtype comparisons

### ISSUE THREAD

**Issue by gbarta** [HIPS/autograd#82]
(I noticed this issue in the sampyl MCMC library and initially logged it there as https://github.com/mcleonard/sampyl/issues/14 and in that issue autograd dev mattjj suggested that a fix could be possible in autograd)

The code is checking that a numpy array contains integral values like: `if x.dtype != np.int_:` but because it is using the autograd wrapped np.int_, the check throws an exception because it is treated as an unknown dtype.

A simple example is attached in [test_dtypes.py.txt](https://github.com/HIPS/autograd/files/76629/test_dtypes.py.txt)

Thanks!

**Comment by gbarta** [comment]
Except, it was fixed while I typed in the issue. Great work :)

**Comment by mattjj** [comment]
Sorry to beat you to the punch :) Let us know if there's any more trouble with this bug.
