### ISSUE TITLE
Bug with numpy.linalg.inv derivative

### ISSUE THREAD

**Issue by gngdb** [HIPS/autograd#83]
I could be making a mistake here, but I'm getting a strange bug when trying to take derivatives of `numpy.linalg.inv`, which it looks like should be supported. The weird part is I can take derivatives, but only after `from autograd.util import *`. I've got an example notebook illustrating the problem [here][].

[here]: http://nbviewer.jupyter.org/gist/gngdb/93724ec941b8954606fd

**Comment by mattjj** [comment]
You need to import autograd.numpy instead of regular numpy. Try replacing this line:

```python
import numpy as np
```

with this one:

```python
import autograd.numpy as np
```

Please reopen if that was not the issue!

**Comment by gngdb** [comment]
That fixes it. Looks like I overlooked that line in all the examples and tutorials. How come it works at all when I don't do that?

**Comment by mattjj** [comment]
My understanding is that some numpy functions dispatch to the object on which they are called, like `np.sum` looks for a `sum` method on its argument. That way it can get into the autograd wrapper even if the `np.sum` being called isn't autograd's version. That only works in some special cases, though, and I don't know what those cases are (it depends on the idiosyncrasies of numpy).
