### ISSUE TITLE
Feature request: forward mode and efficient jacobian-vector product

### ISSUE THREAD

**Issue by j-towns** [HIPS/autograd#89]
As described in [Pearlmutter 2015](http://arxiv.org/pdf/1502.05767v2) section 3.1, or using another method to compute this efficiently if one exists.

This would be useful for the [toolbox](https://github.com/j-towns/pymanopt) we are currently writing.

**Comment by mattjj** [comment]
Currently the `gradfun`s which we define for each primitive compute vector-Jacobian products, with the vector on the left (a Theano "Lop"). I think to support this feature (i.e. computing Jacobian-vector products, or the Theano "Rop") we could add a second kind of gradfun to each primitive which computes its Jacobian-vector product (effectively applying the adjoint of the Jacobian operator the current gradfuns apply). Then we'd need to write another `forward_pass` function in core.py which just carries along those auxiliary variables (without a tape).

On a related note, maybe we should rename "gradfun" to "apply_jacobian_adjoint", and so the new functions we'd add could be called "apply_jacobian".

**Comment by j-towns** [comment]
That sounds like the right way to do it, I'm happy to lend a hand with this if you would like.

**Comment by j-towns** [comment]
A branch with forward mode can be found at https://github.com/j-towns/autograd/tree/forward-mode-new-core.

Not going to be merge for the time being because we don't have a solid use case.
