### ISSUE TITLE
Inherit docstrings from numpy functions

### ISSUE THREAD

**Issue by nirum** [HIPS/autograd#9]
Calling `import autograd.numpy as np` does not inherit numpy docstrings (see below)

Autograd:
![screen shot 2015-04-01 at 2 28 57 pm](https://cloud.githubusercontent.com/assets/904854/6953020/70308a86-d87b-11e4-94c7-4f690dbe9091.png)

Standard numpy:
![screen shot 2015-04-01 at 2 27 59 pm](https://cloud.githubusercontent.com/assets/904854/6953013/56d3b19e-d87b-11e4-81c1-4faedc298420.png)

Would it be possible to use `functools.wraps` in some clever way [1] as to preserve the docstrings?

[1] http://stackoverflow.com/questions/2025562/inherit-docstrings-in-python-class-inheritance

(this isn't a huge issue, but keeping docstrings would be nice)

**Comment by mattjj** [comment]
I think @dougalm fixed this in f42fe48. Your test example seems to work on the current master. Please reopen if I'm mistaken.
