### ISSUE TITLE
Binary Classifier - Log loss function

### ISSUE THREAD

**Issue by andrewcz** [HIPS/autograd#92]
Hi,
Fantastic Library!
I was just wondering, i am trying to use the library for a binary classifier experiment using the log loss function to train the model. This is for a university experiment around benchmarking different models. Would you have time to provide an example of how to use the library to achieve the above goal.
Also showing a visualization in how the algorithm learns and decreases the error.
Many thanks,
Best,
Andrew

**Comment by mattjj** [comment]
Glad you like the library! I don't think making that specific example is within our purview, but good luck with your experiments.
