### ISSUE TITLE
Question: Is it possible to implement LDA using blackbox SVI ?

### ISSUE THREAD

**Issue by viveksck** [HIPS/autograd#94]
Thanks for releasing the code for blackbox SVI using autograd. I am reading your paper: http://people.seas.harvard.edu/~dduvenaud/papers/blackbox.pdf where you outline how to use blackbox SVI. I just wanted to know if models like LDA are supported by your toolkit.

**Comment by mattjj** [comment]
If I understand your question, the shortest answer is yes: pretty much the only function that autograd provides is `grad`, which is meant to be able to differentiate as many Python functions as possible.

In the case of black box SVI, that may mean either that you're using the gradient of the variational family log density inside a Monte Carlo score function estimator, or that you're using the "reparameterization trick" to construct a Monte Carlo estimate of the ELBO itself and then computing that gradient. In either case, `grad` should be able to compute gradients for you.
