### ISSUE TITLE
Create signed distance function from a set of points in 2D or 3D

### ISSUE THREAD

**Issue by liubenyuan** [HIPS/autograd#96]
Hi, I want to describe a curve or surface using signed distance function specified by a set of points,  and calculate its gradient using `autograd`. The question is, how to build an `autograd` compatible (and computational efficient) `sdf` from a set of points ?

**Comment by mattjj** [comment]
Just write the function as you would with numpy. Autograd should be able to differentiate pretty much any numpy code, and writing something to be efficient for numpy makes it efficient for autograd. There aren't any special tricks.
