### ISSUE TITLE
grad of tensordot fails with axes=[[-1], [0]] and works with axes=1

### ISSUE THREAD

**Issue by MInner** [HIPS/autograd#98]
Hi, you library is really awesome, thank you, guys :)

Both two lines above are valid numpy code and do the same thing:
```
np.tensordot(np.random.rand(10, 30), np.random.rand(30, 15), axes=[[-1], [0]])
np.tensordot(np.random.rand(10, 30), np.random.rand(30, 15), axes=1)
```

but taking `autograd.grad` over the first one raises `ValueError` in `transpose` because this piece of code computes invalid axes transposition:
```

    336         sorted_axes_pairs = sorted(zip(X_axes_summed, Y_axes_summed), key = lambda x : x[1])
    337         forward_permutation = ([i for i in range(anp.ndim(X)) if i not in X_axes_summed]
    338                              + [i for i, _ in sorted_axes_pairs])
    339         reverse_permutation = list(anp.argsort(forward_permutation))
    340         if result.ndim == 0:
    341             result = result[()]
--> 342         return anp.transpose(result, axes=reverse_permutation)
```

The error reproduces in a very basic n-dimensional MPL like this:

```
def r_func(H, W1, W2):
    """ H (.., h) -> (.., m) -> (.., h)"""
    relu = lambda x: np.maximum(0, 1-x)
    L1 = relu(np.tensordot(H, W1, axes=1))
    return np.tensordot(L1, W2, axes=1)
```

If you think that's really a bug (not me doing something wrong), I can try to come up with a short fix :)

Ben

**Comment by mattjj** [comment]
Thanks for catching this! It turns out we weren't properly handling negative axis indices passed in the `axes` list. The new code converts negative indices to positive indices, so I think it should work. I added a pretty basic test for this use case, patterned off your example.

Please re-open if this fix doesn't suffice.

Glad you like the project!
